### ISSUE TITLE
Vertical alignment issue of the text and the icon inside button

### ISSUE THREAD

**Issue by sanketsahusoft** [GeekyAnts/NativeBase#10]
![image](https://cloud.githubusercontent.com/assets/1733433/15044418/30c2daa4-12f2-11e6-9552-742a690e0466.png)

I think we need to pull up the icon a bit.

**Comment by sankhadeeproy007** [comment]
That has been fixed with `v0.3.0` :)

**Comment by sanketsahusoft** [comment]
@SupriyaKalghatgi The doc still shows old icons then
http://nativebase.io/docs/v0.3.0/components#button
