### ISSUE TITLE
react-native iOS app cannot run due to native-base module error

### ISSUE THREAD

**Issue by santosh-btc** [GeekyAnts/NativeBase#1029]
Error Log:

```
error: bundling: UnableToResolveError: Unable to resolve module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` from `/Users/hiteshmac/Documents/ReactApp/santosh/Connect3App/node_modules/native-base/dist/src/Utils/computeProps.js`: Module does not exist in the module map or in these directories:
  /Users/hiteshmac/Documents/ReactApp/santosh/Connect3App/node_modules/native-base/node_modules/react-native/Libraries/Renderer/shims
,   /Users/hiteshmac/Documents/ReactApp/santosh/Connect3App/node_modules/react-native/Libraries/Renderer/shims
```

package.json

```
  "dependencies": {
    "Base64": "^1.0.1",
    "babel-plugin-transform-remove-console": "^6.8.4",
    "buffer": "^5.0.6",
    "native-base": "^2.1.4",
    "pubsub-js": "^1.5.7",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-android-wifi": "0.0.13",
    "react-native-background-timer": "^1.0.3",
    "react-native-deprecated-custom-components": "^0.1.0",
    "react-native-hyperlink": "0.0.9",
    "react-native-progress": "^3.2.1",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-table-component": "^1.0.1",
    "react-native-udp": "^2.0.0",
    "react-navigation": "^1.0.0-beta.11"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "1.9.2",
    "jest": "20.0.3",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  },
  "browser": {
    "dgram": "react-native-udp"
  }
}

```

 **react-native version - 0.44.0**
**native-base version -  ^2.1.4**
![ios_error](https://user-images.githubusercontent.com/14067724/28052820-c33b5b04-662a-11e7-8769-183a987d0f5b.png)

I have spent the whole day behind it. but no luck.

Please Help.

**Comment by shivrajkumar** [comment]
@santosh-btc "native-base": "^2.1.4", `^` here installs the latest of NativeBase i.e, 2.2.1 which works for RN >= 46. Check compatibility here https://github.com/GeekyAnts/NativeBase#6-compatibility-versions.
Remove `^` and it should work for you

**Comment by santosh-btc** [comment]
@shivrajkumar Still same issue.

**Comment by shivrajkumar** [comment]
@santosh-btc Can you post the steps you followed, the issue screenshot which you got after that and also add package.json content here.

**Comment by ElliottJRo** [comment]
@shivrajkumar @santosh-btc Found the reason why: https://github.com/GeekyAnts/react-native-easy-grid/commit/d87343be45440b42c65b532ee90837c71a508d07

Apparently it was fixed with https://github.com/GeekyAnts/react-native-easy-grid/commit/43fd6ff49788a27ddc28e4bf364f28cd39c18e46

But for some reason 0.1.13 was released then another was released 0.1.11 (which works with rn 0.46) https://github.com/GeekyAnts/react-native-easy-grid/issues/41

Current fix: Add `"react-native-easy-grid": "0.1.11"` to dep
Also added `"color": "0.11.1"` since I am am using custom theme

**Comment by markgoodyear** [comment]
I'm getting the same issue.

@ElliottJRo I've tried doing this, deleted `node_modules` and used npm instead of yarn to install, and I still get the same issue.

**Comment by ElliottJRo** [comment]
@markgoodyear what version of RN are you using? it should be 0.46.1

**Comment by markgoodyear** [comment]
@ElliottJRo I used CRNA, and just realised that it's not using the latest RN, it's on 0.45.1. Switched to NativeBase v2.2.0 and all is working.
