### ISSUE TITLE
Deckswiper does not update after state update

### ISSUE THREAD

**Issue by abeltje1** [GeekyAnts/NativeBase#1092]
react native v0.40, react v15.4.2 native-base v2.1.0

It's hard to get a deckswiper to work with data fetched from an API. When I initialize the deckswiper with an empty array and fill that array a little bit later (when the data is fetched) the deckswiper does not update. This means if my data changes at any given point, it's impossible to update the deckswiper accordingly. I had to conditonally render the deckswiper (only render if array is not empty) to get it to work at all, but the problem of updating data in real-time still exists and I do not see any other way of hacking around this. Love the UI of the component, but my guess is nearly every app needs this kind of functionality so it'd be very nice to have.

`{this.state.items.length > 0 && !this.state.firstLoad ? <DeckSwiper ref={(c) => this._deckSwiper = c} onSwipeLeft = {() => this._deckSwiper._root.swipeLeft()}
                        dataSource={this.state.items}
                        renderItem={(item) => 
                           <View><Text> {item.title}</Text><HTMLView value={item.content} renderNode={renderNode}></HTMLView><Text>{item.team_naam} </Text></View>}/> : <Text> yo </Text>}`

(the state. firstLoad is used for transitioning from background to foreground). I'm really curious whether this (lack of) functionality was intended, a bug or if I'm missing something. Would be very glad to hear from you and last but not least: great work with native-base.

**Comment by shivrajkumar** [comment]
@abeltje1 This has been fixed in the later versions. i.e, NativeBase > 2.1.5

**Comment by abeltje1** [comment]
thanks! great!

**Comment by hoekma** [comment]
I am still having this issue on native-base 2.3.2.  Using Redux reducer for state, if I seed it with an array, cards render.  But after changing state with data from the server, there is no update of the DeckSwiper cards.  I can log to console and see that the array assigned to dataSource has changed, but the cards do not change.

**Comment by SupriyaKalghatgi** [comment]
@hoekma did you find it working?

**Comment by hoekma** [comment]
Yes  I did. I would up binding to a variable that I created in the render
method and populated the variable with a method inside of the same class
that returned the prop to which the redux state was mapped.

**Comment by SupriyaKalghatgi** [comment]
Nice @hoekma

**Comment by 123lk** [comment]
@hoekma could you show an example of your code?  I'm having the same issue with deckswiper but haven't figured out how to implement the fix that you suggest (binding the datasource to a variable)

**Comment by hoekma** [comment]
@123lk 

I've actually moved away from deckswiper for other reasons, but here is the idea...  

`class Home extends Component {
    static navigationOptions = {
        title: 'Home'
    }

    constructor(props) {
        super(props);
        this.state = {
            searching: false,
            isReady: false,
        }
    }

    async componentWillMount() {
        if (!this.assetsFound()) {
            this.loadAssets();
        }

        this.setState({ isReady: true });
    }

    // Loads assets. using fetchAssets from assets.action.js
    loadAssets = () => {
        this.props.fetchAssets(this.props)
    }

    // map assets objects for use in the render() method
    assets = () => {
        return Object.keys(this.props.assets)
            .map(key => this.props.assets[key])
            .sort(function (a, b) {
                var retVal = 0;
                if (a.transactions[0] != null && b.transactions[0] != null) {
                    // push it up the sort order if it is a more recent transaction
                    retVal = a.transactions[0].created_at > b.transactions[0].created_at ? -1 : 1;
                } else if (a.transactions[0] == null) {
                    // push it down the sort order if a doesn't have any transactions
                    retVal = 1
                }

                return retVal;
            })
    }

    // returns number of assets in the redux state.
    assetsFound = () => {
        return this.props.assetCount > 0
    }

    render() {
        // console.log('Home Container')
        // console.log(this)
        if (!this.state.isReady) {
            return <View><Text>Loading....</Text></View>
        }

        const { dispatch, navigationState } = this.props;
        const txtUpdated = 'Updated ';

        if (this.props.isAuthenticated) {
            // NEXT LINE THIS IS THE PLACE THAT REFRESHES THE DATA FOR THE DECKSWIPER
            // IT WILL REFRESH EACH TIME RENDER EXECUTES
            const cardAssets = this.assets() 
            return (
                <Container>
                    <Header style={Styles.header}>
                        <Body>
                            <Title>Home</Title>
                        </Body>
                    </Header>
                    <Content style={Styles.content} >
                             // BIND cardAssets to deckSwiper.  
                            <DeckSwiper datasource={cardAssets} renderItem={item => 
                                    <Card>... YOUR STUFF HERE></Card>
                                    <Card>... YOUR STUFF HERE></Card>
                                    <Card>... YOUR STUFF HERE></Card>
                                }/>
                    </Content>
                    <Footer>
                        <FooterTab>
                            <Button onPress={() => this.loadAssets()} active style={Styles.footerButton}>
                                <Icon name="refresh" />
                            </Button>
                            <Button onPress={() => this.props.navigation.navigate('ScreenUserSettings')} active style={Styles.footerButton}>
                                <Icon name="person" />
                            </Button>
                        </FooterTab>
                    </Footer>
                </Container>
            )
        } else { return <View><Text>Not authenticated</Text></View> }
    }
}
`

**Comment by 123lk** [comment]
Thank you @hoekma!
