### ISSUE TITLE
`Picker` component performance issues on iOS with larger items

### ISSUE THREAD

**Issue by aligfl** [GeekyAnts/NativeBase#1239]
Hi,
I'm seeing some performance issues when using the `Picker` component with large items on iOS.

## react-native, react and native-base version
```
...
"native-base": "^2.3.1",
"prop-types": "^15.5.10",
"react": "16.0.0-alpha.12",
"react-native": "^0.46.0",
...
```
## Expected behaviour
Picker to quickly close when an item is selected or `back` button is pressed.

## Actual behaviour
There is a 3~4 second lag when either an item is selected or `back` is pressed on iOS

## Steps to reproduce (code snippet or screenshot)
1. Use the following picker, with around `800` items.
2. Open the Picker by clicking on it
3. Press `back` OR select an item from the list.

```
    <Picker
      selectedValue={5}
    >
      {
        Array(800).fill().map((e,i)=>i+1).map((i, index) => (
          <Item label={i} value={i} key={i} />
        ))
      }
    </Picker>
```
## Screenshot of emulator/device
![sep-18-2017 21-33-02](https://user-images.githubusercontent.com/23323932/30571986-0fdcaa70-9cb9-11e7-8d7b-9e2de835f4d5.gif)

## Is the bug present in both ios and android or in any one of them?
just iOS.

**Comment by akhil-geekyants** [comment]
@aligfl 800 items in picker is a very large number. We don't generally use such a large number of items in picker. If there is any valid use case, let us know.

**Comment by aligfl** [comment]
@akhil-geekyants this is a use case for our app. Where we have a list of items that we need to pick from. Infact ours is around even more. I used 800 just as an example. It would be great if the performance problem can be fixed.

It would be amazing if you guys added a "Search Bar" at the top to search the list of item from the picker.

**Comment by akhil-geekyants** [comment]
@aligfl For such a large number of items you can use React Native FlatList with Picker. That can improve the performance.

**Comment by SupriyaKalghatgi** [comment]
@aligfl We will have React Native's FlatList with NativeBase Picker

**Comment by brunolemos** [comment]
@aligfl 

1. You should not use `.map` with big lists, use `FlatList` instead.
2. Do not use index as keys

So this seems to be a normal list performance issue, not necessarily related to Picker.

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.6](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.6)

**Comment by neekey** [comment]
I'm still having this performance issue with version `^2.12.1`. In my case, I only have around 150 items.

The main problem I can observe is that the rendering of the items happens even the List is not active, say I have this edit page with this big picker, when I click a link from another page to this edit page, the screen will freeze for several seconds, then the edit page appears.

the list should only be rendered when the picker is active IMO
