### ISSUE TITLE
icon.props is undefined. 

### ISSUE THREAD

**Issue by zibs** [GeekyAnts/NativeBase#137]
Hi all,

I've seen this error pop up in a couple of different places for various reason. I'm thinking it has something to do with trying to render dynamic content inside of a button/input group specifically. 

``` javascript
<Button block bordered> {"this doesnt work"} </Button>
```

This will throw an icon.props undefined error. 

The same thing happens when I try to render an icon depending on if it should be rendered or not. The detectIconToRender function would return null if there is no function to render

``` javascript
<InputGroup borderType='underline' >
      {this.detectIconToRender()} 
   <Input placeholder='Dynamic Icons' />
</InputGroup>
```

As mentioned, both of these cases return an icon.props undefined error. 

I've looked in the code and it seems that dynamically rendered content is getting interpreted as iconLeft as it attempts to render the content of the button/input group. 

Thanks!

**Comment by sankhadeeproy007** [comment]
We too have come across this bug and it's annoying. Will fix it sometime in the near future.

**Comment by sankhadeeproy007** [comment]
Fixed with v0.5.20

**Comment by JulianKingman** [comment]
I'm getting this issue with a button that has iconLeft, I'm on 0.5.22, here's what it looks like (using react-native-vector-icons/MaterialIcons):
````javascript
<Button block transparent large iconLeft onPress={this.toggleDatePicker}>
  <Icon name="event"/>
  {this.formatDate(this.state.selectedDate)}
</Button>
````
Stripping it down, I still get the error with just this:
````javascript
<Button iconLeft>
  <Icon name="event"/>
  <Text>Button</Text>
</Button>
````
