### ISSUE TITLE
Invalid prop 'name' on icon

### ISSUE THREAD

**Issue by fullhdpixel** [GeekyAnts/NativeBase#1468]
Here is my markup:

```
<Form>
  <Item>
    <Icon name="user" color={colors.background} />
    <Input placeholder="Username" />
  </Item>
  <Item last>
    <Icon name="unlock" color={colors.charcoal} />
    <Input placeholder="Password" />
  </Item>

  <Button full rounded style={styles.loginButton}>
    <Text>Login</Text>
  </Button>
</Form>
```

The Icon name="user" does not work, however the icon with name="unlock" is perfect. I want to use the icon from the EvilIcons namespace.

Referencing this error:
https://github.com/react-native-training/react-native-elements/issues/183

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.6](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.6)

**Comment by HaswinVidanage** [comment]
I believe the issue still exists. Gives me the Invalid prop 'name' on icon 

`<Icon name='ei-chevron-right' />`
 
Native Base Version
> "native-base": "^2.3.6",

**Comment by SupriyaKalghatgi** [comment]
@HaswinVidanage Fixed with NB [2.3.10](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.10)

**Comment by SupriyaKalghatgi** [comment]
Can you try this with latest NativeBase?

**Comment by shuiRong** [comment]
still exists
```
 <Icon name="logout"  />
```
version: `"native-base": "^2.8.1"`

**Comment by Mahdiyeh** [comment]
> still exists
> 
> ```
>  <Icon name="logout"  />
> ```
> 
> version: `"native-base": "^2.8.1"`

I wrote the name "md-log-out" and it works in both iOS and Android.

`<Icon size={30}  name="md-log-out"  style={{color: '#FDBE51'}} />`
