### ISSUE TITLE
No padding for ListItem Text / icon

### ISSUE THREAD

**Issue by amirfl** [GeekyAnts/NativeBase#155]
When using a ListItem with a left icon, copy-pasted from the example at http://nativebase.io/docs/v0.5.7/components#list, I'm getting no padding between the icon and the text.
![screen shot 2016-09-01 at 1 10 56 pm](https://cloud.githubusercontent.com/assets/364326/18176883/a0166848-7045-11e6-9ef5-48a36ff1913f.png)

**Comment by SupriyaKalghatgi** [comment]
@amirfl Did you make changes in theme file?

**Comment by amirfl** [comment]
I did, based on Native-Starter-Kit's theme. However, even if I remove the call to use the theme ( `<Container` **theme={myTheme}**`> `), the icons are still not padded. I worked this around for now by simply adding a style to the icons.

**Comment by SupriyaKalghatgi** [comment]
@amirfl I tried the same example from docs, padding works fine.
And that is not an extra empty row added there, its a bug as NativeBase List is not working fine with `iconRight` and `iconLeft` both used in single `ListItem`.
To be fixed soon.
 ![screen shot 2016-09-06 at 7 32 49 pm](https://cloud.githubusercontent.com/assets/13464885/18276479/bf25b91a-7468-11e6-9e4b-2434e5e9d676.png)

**Comment by amirfl** [comment]
I can't find out why its doing this inside my project, even after removing the reference to the theme. Since its working in a clean project, it might be a problem with my code so I'll close the issue

**Comment by SupriyaKalghatgi** [comment]
@amirfl Fixed with 0.5.8

**Comment by ar-nit** [comment]
![screenshot 66](https://cloud.githubusercontent.com/assets/11644819/19012249/496868c8-87da-11e6-87ef-aa883c5da901.png)
Hi! guy, How to fix padding between Home button and another ? (I try v0.5.8 and v0.5.9 latest).

**Comment by andrewnoh** [comment]
![screen shot 2016-10-05 at 10 13 28 pm](https://cloud.githubusercontent.com/assets/13257645/19138345/38288fd0-8b49-11e6-865b-0421fb9f837c.png)

I am still having this issue on 0.5.9.

**Comment by ALawliet** [comment]
Use ```import { Text } from 'native-base'``` instead of ```import { Text } from 'react-native'```

**Comment by SupriyaKalghatgi** [comment]
@ar-nit For the purpose of demonstration, we have included extra padding between the components. This is not the case with all components. Also, this has been on our list.
NativeBase will be fixed with these issues in its upcoming sprint.

**Comment by ALawliet** [comment]
For people still having this issue, ```import { Text } from 'native-base'``` NOT react-native. I saw this happen on 0.59 when I imported from react-native.

**Comment by SupriyaKalghatgi** [comment]
@ALawliet Can you please elaborate

**Comment by Cengkaruk** [comment]
Hi. Some Ionicons are comes with different width. I try to solve this problem by add padding at Icon manually.

![screen shot 2016-12-12 at 2 25 18 pm](https://cloud.githubusercontent.com/assets/629402/21091207/5249dcb2-c077-11e6-8f22-683fcf9657fd.png)

**Comment by sanketsahusoft** [comment]
@Cengkaruk Yes, that's how it is. They're glyphs and glyphs have different width. You can wrap a <View /> and provide a width if needed.

**Comment by mentalMedley** [comment]
Now (v2.2.0) you need to add only `icon` prop instead of `iconLeft` and `iconRight`. Example:
```
<ListItem icon>
  <Left>
    <Icon name="ios-alarm"/>
  </Left>
  <Body>
    <Text>Schedule</Text>
  </Body>
  <Right>
    <Text>Open now</Text>
    <Icon name="arrow-forward"/>
  </Right>
</ListItem>
```
