### ISSUE TITLE
Can not change size of Badge element

### ISSUE THREAD

**Issue by yaronlevi** [GeekyAnts/NativeBase#159]
According to [this cheat sheet](http://nativebase.io/docs/v0.5.7/cheatsheet) I should be able to change the badge's size. I've tried:
`<Badge success style={{fontSize:5, width:10}}>99</Badge>`
But I get those errors in runtime:
![screen shot 2016-09-04 at 8 17 27 am](https://cloud.githubusercontent.com/assets/5398977/18229199/10585c4a-7278-11e6-9e0b-a4b63fbe2a53.png)

So how can I change the badge's size?

"native-base": "^0.5.7"
"react": "^15.3.0"
"react-native": "^0.32.0"
Run on iOS simulator.

**Comment by SupriyaKalghatgi** [comment]
@yaronlevi Docs has been updated
Please check and try accordingly

**Comment by yaronlevi** [comment]
Can you give me a link? I can not seem to find the change

**Comment by SupriyaKalghatgi** [comment]
@yaronlevi The same link which you shared

**Comment by SupriyaKalghatgi** [comment]
@yaronlevi Try clearing your cache

**Comment by yaronlevi** [comment]
Is this what the updated docs looks like?
![screen shot 2016-09-06 at 11 04 52 am](https://cloud.githubusercontent.com/assets/5398977/18266140/d4725658-7421-11e6-8bf7-1888ebcdd7dc.png)

**Comment by SupriyaKalghatgi** [comment]
Check the replacing component for Badge
![screen shot 2016-09-06 at 1 36 27 pm](https://cloud.githubusercontent.com/assets/13464885/18266182/13cc7e0e-7437-11e6-8c1f-853a19232c3d.png)
Also check the code for Badge.
NB wraps `Text` within `View`, so you cannot apply `style={{fontSize:5, width:10}}` to `View`

**Comment by SupriyaKalghatgi** [comment]
@yaronlevi 
![screen shot 2016-09-06 at 1 39 36 pm](https://cloud.githubusercontent.com/assets/13464885/18266245/74baba78-7437-11e6-99f6-834b82c41e32.png)
This says the same

**Comment by yaronlevi** [comment]
Ok, so I changed the code to:
`<Badge success width={10} fontSize={5}>3</Badge>`
And this is what I get:
![screen shot 2016-09-06 at 11 25 37 am](https://cloud.githubusercontent.com/assets/5398977/18266706/a70d2a64-7424-11e6-9064-142b68a0f7f3.png)

Can you please tell me how can I take the default Badge, and just make it smaller (both font size and the size of the circle).

**Comment by SupriyaKalghatgi** [comment]
@yaronlevi Sorry for misguidance.
This issue has been fixed, please pull from `master`.
Also docs has been updated accordingly - [Badge Component](http://nativebase.io/docs/v0.5.7/components#badge) and [CheatSheet](http://nativebase.io/docs/v0.5.7/cheatsheet)

**Comment by yaronlevi** [comment]
Still not working, my code is:
```
<Badge  style={{ width: 30, backgroundColor: 'black' }}
                                textStyle={{ color: 'white', fontSize: 10, lineHeight: 10 }}>
                                2
                            </Badge>
```

The fontSize and lineHeight seems to have no effect. The font size stays the same:
![screen shot 2016-09-06 at 1 58 02 pm](https://cloud.githubusercontent.com/assets/5398977/18271268/f1718e64-7439-11e6-9710-0dd6b66ea9e2.png)

**Comment by sankhadeeproy007** [comment]
Hi @yaronlevi, can you check the contents of `Widgets/Badge.js` and post a screenshot of the same?

**Comment by yaronlevi** [comment]
Ah ok my mistake. I've updated the npm to look at the repositoty.
`"native-base": "github:geekyants/NativeBase",`
No it works... I have the updated file.

**Comment by sankhadeeproy007** [comment]
Good to know!

**Comment by remoteportal** [comment]
Unless the badge can be made smaller, it's useless.

**Comment by khalibloo** [comment]
Here's my workaround. Simply scale the whole thing instead of using font size and line height.
`<Badge style={{scaleX: 0.7, scaleY: 0.7}} primary><Text>1</Text></Badge>`
I don't know if it has any drawbacks or how well it works for extreme scales, but it should cover simple minor adjustments at the very least.
