### ISSUE TITLE
tabFontSize not working (material.js - ejectedTheme)

### ISSUE THREAD

**Issue by theapache64** [GeekyAnts/NativeBase#1992]

**Comment by SupriyaKalghatgi** [comment]
Fixed with [v2.5.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.5.2)

**Comment by theapache64** [comment]
It's still not working. Am using v2.6.1. Here's the source code
[TabFontSizeTest.zip](https://github.com/GeekyAnts/NativeBase/files/2129792/TabFontSizeTest.zip)

**Comment by theapache64** [comment]
Confirmed. It's working now (y)
