### ISSUE TITLE
Can't use style provider.

### ISSUE THREAD

**Issue by vtur** [GeekyAnts/NativeBase#2581]
When I do the same on android it worked perfectly. But when I even try to use StyleProvider in clear ios app I have this error: http://prntscr.com/ml33gq.
Code: http://prntscr.com/ml36rg
Help me please.

**Comment by vtur** [comment]
And if we will not found way to use styleProvider, how I can change style of active tab?

**Comment by vtur** [comment]
If I use Platform.js instead Material.js it works good.

**Comment by SupriyaKalghatgi** [comment]
Fixed with commit https://github.com/GeekyAnts/NativeBase/commit/4c8a68b1886bfd1eca8d976d72726ffe6062bc94

**Comment by dl-husky73** [comment]
Thanks, that cleared up my first issue (first & main user screen).  Still getting the issue on deckswiper screen, except now my two NaN messages are paddingleft & paddingright, each with : NaN.  The invariant violation is 439.   Is this the same issue as above?

**Comment by SupriyaKalghatgi** [comment]
Sorry! Cant help without screenshot and type of simulator
Do mention if any of the `native-base-theme/variables` file is causing this issue

**Comment by dl-husky73** [comment]
Sorry, here is a screen shot.  As I said works on previous screens based on above fix.  This is a deckswiper screen.  Any help would be great. 
![image](https://user-images.githubusercontent.com/47721681/53179112-1a6fb700-35c1-11e9-8bdd-1ad1167a296b.png)

**Comment by dl-husky73** [comment]
Oh and in response to your question, I am using a custom theme created with the customizer.  I have used a custom file in the variables directory, based on material theme.

**Comment by SupriyaKalghatgi** [comment]
I tried NativeBase KitchnSink app with default `material` theme, no issues with it

**Comment by dl-husky73** [comment]
Hi, I appreciate the reply.  I updated to 2.12 Native Base, used the customizer again to create custom theme.  Ejected the theme and tried styleprovider with GetTheme again.  Works in most screens but not in this case.  I still get the same error,  (paddingLeft NaN, paddingRight NaN).  Seems same as other problem last week.   I included error and code, is an annoying problem not allowing me to use NB theme throughout.   Any help?  
![image](https://user-images.githubusercontent.com/47721681/53372175-30aea780-3920-11e9-94aa-4b06c371ade9.png)

Here is the code if you want to see:

   <StyleProvider style={getTheme(customGuideslyTheme)}>
      <Container>
        <Header>
          <Left>
            <Button transparent>
              <Icon name='arrow-back' />
              <Text>back</Text>
            </Button>
          </Left>
          <Body>
            <Title>Select A Guide</Title>
          </Body>
          <Right>
          <Title>{val1.guidename}</Title>
          </Right>
        </Header>
        <Content>
        <DeckSwiper
          ref={(c) => this._deckSwiper = c}
         // dataSource={this.state.dataSource}
         dataSource={val1}
          renderEmpty={() =>
            <View style={{ alignSelf: "center" }}>
              <Text>End of Guides</Text>
            </View>
          }
          renderItem={item =>
            <Card>
              <CardItem>
                <Left>
                <Thumbnail style={{width: 100, height: 100, borderRadius: 100/2}} source={guideImage[(item.guideid-1)]} />
                  <Body>
                    <Text>{item.guidename}</Text>
                    <Text>{item.city}, {item.state}</Text>
                    <Text>{item.company}</Text>
                    <Rating
                      type="star"
                      fractions={1}
                      startingValue={Number(item.rating)}
                      readonly
                      ratingColor='#086641'
                      imageSize={20}
                      onFinishRating={this.ratingCompleted}
                      style={{ paddingVertical: 5 }}
                    />
                  </Body>
                </Left>
              </CardItem>
              <CardItem cardBody>
                {item.fishingtype.map((object, key) => 
                  <Button rounded small success key={key}><Text>{object}</Text></Button>)
                }
              </CardItem>
              <CardItem cardBody>
                  <Text>{item.description}</Text>
              </CardItem>
              <CardItem cardBody>
                  <Body >
                    <Button rounded primary><Text>Select Date</Text></Button> 
                      <Button rounded disabled={this.state.isDate} primary onPress={() => this.props.navigation.navigate('BookGuide1', {
                            guideid: item.guideid,
                            guideguid: item.guideguid})}>
                        <Text>Book Guide</Text></Button>
                  </Body>
              </CardItem>
            </Card>
          }
        />
      </Content>
    </Container>
    </StyleProvider>
