### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by sajaddp** [GeekyAnts/NativeBase#2776]
Hi,
```
Warning: componentWillUpdate is deprecated and will be removed in the next major version. Use componentDidUpdate instead. As a temporary workaround, you can rename to UNSAFE_componentWillUpdate.

Please update the following components: DrawerLayout, IconNB

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

Version:
```
react: 16.8.6
react-native: 0.60.3
native-base: 2.12.1
```

**Comment by IntelliJAbhishek** [comment]
+1

lots of warning in latest RN 60.x

**Comment by knap1930** [comment]
there is also 

```
Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.
```

```
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.
```

**Comment by kukokp** [comment]
How to use in RN 0.60.3 ?
Any one please guide!!!

**Comment by knap1930** [comment]
temporary solution is to add this to your index.js until they have a chance to update

```
import { YellowBox } from 'react-native';

YellowBox.ignoreWarnings([
    'Warning: componentWillMount is deprecated',
    'Warning: componentWillUpdate is deprecated',
    'Warning: componentWillReceiveProps is deprecated',
]);
```

**Comment by IntelliJAbhishek** [comment]
> How to use in RN 0.60.3 ?
> Any one please guide!!!
> 
> Without autolink!
> however to add .
> I need some guidance to implement .

@kukokp we are getting lots of warning.

> temporary solution is to add this to your index.js until they have a chance to update
> 
> ```
> import { YellowBox } from 'react-native';
> 
> YellowBox.ignoreWarnings([
>     'Warning: componentWillMount is deprecated',
>     'Warning: componentWillUpdate is deprecated',
>     'Warning: componentWillReceiveProps is deprecated',
> ]);
> ```

@knap1930 Its a bad idea

**Comment by kukokp** [comment]
@IN

> > How to use in RN 0.60.3 ?
> > Any one please guide!!!
> > Without autolink!
> > however to add .
> > I need some guidance to implement .
> 
> @kukokp we are getting lots of warning.
> 
> > temporary solution is to add this to your index.js until they have a chance to update
> > ```
> > import { YellowBox } from 'react-native';
> > 
> > YellowBox.ignoreWarnings([
> >     'Warning: componentWillMount is deprecated',
> >     'Warning: componentWillUpdate is deprecated',
> >     'Warning: componentWillReceiveProps is deprecated',
> > ]);
> > ```
> 
> @knap1930 Its a bad idea

@IntelliJAbhishek  Are you checked this.
I resolved migration issue.
But still facing some issue like GeoLocation.

**Comment by IntelliJAbhishek** [comment]
@kukokp geolocation replaced by https://github.com/react-native-community/react-native-geolocation

**Comment by radenaryayusuf** [comment]
anyone have fixed for this issue? also it's getting more Lag after i use RN 0.60.3 x NativeBase

**Comment by Eldavid** [comment]
I have this issue on the following stack:
```   
"native-base": "^2.12.2",
"react": "16.8.6",
"react-native": "0.60.4",
```

Its really annoying, even i can hide from yellowbox, but the console is full of with these errors. @radenaryayusuf u think its cause performance issue?

**Comment by sankhadeeproy007** [comment]
Fixed in 2.13.0

**Comment by redcomethk** [comment]
I still have this issue on the following stack:
```
"native-base": "2.13.0",
"react": "16.8.6",
"react-native": "0.60.4",
```
I place the `Icon` in the `Item` and still see the `componentWillUpdate is deprecated` yellow warning.

**Comment by IntelliJAbhishek** [comment]
@sankhadeeproy007 looks like more items need to refactor. I m getting lots of warning, Please reopne this issue

> Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

>Please update the following components: HTML, Styled(Body), Styled(Button), Styled(Header), Styled(Icon), Styled(IconNB), Styled(Left), Styled(ListItem), Styled(Right), Styled(Title), withAnimatable(View)


>Warning: componentWillUpdate is deprecated and will be removed in the next major version. Use componentDidUpdate instead. As a temporary workaround, you can rename to UNSAFE_componentWillUpdate.

>Please update the following components: IconNB,

**Comment by sajaddp** [comment]
@sankhadeeproy007  I still have this issue!

**Comment by sankhadeeproy007** [comment]
Please post a snippet which I can use to reproduce.

**Comment by IntelliJAbhishek** [comment]
@sankhadeeproy007 check my comment here. you will understand https://github.com/GeekyAnts/theme/commit/51fcc2334ca225bdcc7a4cb2efcacc7bcbf3e2ef

**Comment by sankhadeeproy007** [comment]
Yes, I see it now. Thanks, will get a fix ready soon 👍

**Comment by gitowiec** [comment]
I still get these issue
Thanks @knap1930 for the ignore trick
This is what I use from NativeBase:
```
import { Body, Container, Content, Footer, Header, Right, Root, Title } from 'native-base';
import { Icon } from 'native-base';
	import { Button, Text } from 'native-base';
import { Card, CardItem, Icon, Text, View } from 'native-base';
```
## Info
```
System:
    OS: Linux 5.1 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
    Memory: 436.35 MB / 15.52 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Deps
```
  "dependencies": {
    "mobx": "^5.13.0",
    "mobx-react": "^6.1.1",
    "native-base": "^2.13.4",
    "polished": "^3.4.1",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-app-intro-slider": "^3.0.0",
    "react-native-home-pressed": "^1.1.4",
    "react-native-svg": "^9.5.3"
  },
```

**Comment by gitowiec** [comment]
This issue should be reopened

**Comment by vkts** [comment]
> This issue should be reopened
This issue has been resurfacing for a year and I wasted hours of my life before I found and read [this](https://github.com/GeekyAnts/NativeBase/issues/1758#issuecomment-379537744)

**Comment by IDS-Danhnc** [comment]
> > How to use in RN 0.60.3 ?
> > Any one please guide!!!
> > Without autolink!
> > however to add .
> > I need some guidance to implement .
> 
> @kukokp we are getting lots of warning.
> 
> > temporary solution is to add this to your index.js until they have a chance to update
> > ```
> > import { YellowBox } from 'react-native';
> > 
> > YellowBox.ignoreWarnings([
> >     'Warning: componentWillMount is deprecated',
> >     'Warning: componentWillUpdate is deprecated',
> >     'Warning: componentWillReceiveProps is deprecated',
> > ]);
> > ```
> 
> @knap1930 Its a bad idea

You can use as follow:
UNSAFE_componentWillReceiveProps(props) {...}

**Comment by NafisAbdullahKhan** [comment]
npx react-codemod rename-unsafe-lifecycles

**Comment by Muhammad-Wasi** [comment]
> npx react-codemod rename-unsafe-lifecycles

still not working

**Comment by Makgora** [comment]
The question is not how to fit it localy but, will they fix that someday ?

**Comment by ngocdaothanh** [comment]
With `react-native` 0.63.4:

```
import {LogBox} from 'react-native'

LogBox.ignoreLogs([
  'componentWillMount',
  'componentWillUpdate',
  'componentWillReceiveProps'
])
```
