### ISSUE TITLE
Uncaught Error: Maximum update depth exceeded in Input onChangeText

### ISSUE THREAD

**Issue by ashishdigitalrooar** [GeekyAnts/NativeBase#2812]
I have updated expo version from 32 to 33. Everything working fine but when try to enter text in input field getting below error.
**Invariant Violation: Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.** 

```
**I have created custom input component** 
export const CustomInput = (props) => {
    const { value, onChange, label = 'Enter', autocapital='none', placeholder, textLength=100, keyboard='default',getRef, style = {}, secureText=false} = props;

    return (
        <Item floatingLabel style={[styles.input,style]}>
            <Label>{props.label}</Label>
            <Input maxLength={textLength} placeholder={placeholder} autoCapitalize={autocapital} keyboardType={keyboard} onChangeText={onChange} getRef={getRef} value={value} secureTextEntry={secureText}/>
        </Item>
    );
};

**Calling in login screen**
<CustomInput textLength={100} label="Email" style={{marginBottom: 30, marginTop: 30}} keyboard="email-address" value={email} 
                      onChange={email => this.setState({email: email.trim()})}
                      />

**I have also tried with simple code without my custom input component** 
 <Item floatingLabel>
       <Label>Email</Label>
       <Input maxLength={100} keyboardType={'email-address'} onChangeText={(text) => this.setState({email: text.trim()})} value={email}/></Item>
```

In every condition getting same error.

**Comment by sankhadeeproy007** [comment]
Duplicate #2810

**Comment by ashishdigitalrooar** [comment]
My error is same with #2810, but its coming in Input.

**Comment by sankhadeeproy007** [comment]
@ashishdigitalrooar Use case? How do I reproduce?

**Comment by ashishdigitalrooar** [comment]
> @ashishdigitalrooar Use case? How do I reproduce?
Issue with onChangeText in Input, when going to enter text in input getting error.
I tested with old version 2.12.2 but no luck 
These configs in my project
"expo": "^33.0.0",
"react": "16.8.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
> <Item floatingLabel>
>        <Label>Email</Label>
>        <Input maxLength={100} keyboardType={'email-address'} onChangeText={(text) => this.setState({email: text.trim()})} value={email}/></Item>

**Comment by ashishdigitalrooar** [comment]
@sankhadeeproy007 What about this thread? Did you resolved in latest release?

**Comment by sankhadeeproy007** [comment]
Can you confirm that this issue persists for all Inputs? Or just inputs with a floating label?
Please check with the latest version.

**Comment by sankhadeeproy007** [comment]
Please check with 2.13.3

**Comment by sankhadeeproy007** [comment]
Please check with 2.13.4

**Comment by ashishdigitalrooar** [comment]
I tested input with 2.13.4, Now its working fine but there are I have used tab in my form Tab not changing after click and not showing active
Thank you :)

**Comment by sankhadeeproy007** [comment]
@ashishdigitalrooar Can you please create a new issue with proper reproduction steps and screenshots/gif?
Closing this one.
