### ISSUE TITLE
Component style not update after props changed

### ISSUE THREAD

**Issue by yoedfried** [GeekyAnts/NativeBase#2814]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
react-native:0.59.10
react: 16.8.6
native-base: 2.13.0

### Expected behaviour
The component style change after props change

### Actual behaviour
The component style stays in the initial style

### Steps to reproduce

`class TwoStateButton extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isChecked: props.initialChecked
    };
  }

  render() {
    const {isChecked} = this.state;

    return (
      <Button ghost={isChecked} active onPress={() => this.setState({isChecked: !isChecked})}>
        <Text style={{color: isChecked ? 'green' : 'red'}}>{isChecked ? 'checked' : 'not'}</Text>
      </Button>
    );
  }
}`

### Is the bug present in both iOS and Android or in any one of them?
both

### Any other additional info which would help us debug the issue quicker.

In the native-base dependancy we have         
"native-base-shoutem-theme": "github:GeekyAnts/theme#master".
At the 23.7 someones commit to the GeekyAnts/theme#master [commit](https://github.com/GeekyAnts/theme/commit/51fcc2334ca225bdcc7a4cb2efcacc7bcbf3e2ef)
he replaced the componentWillRecivedProps to componentcomponentDidUpdate.

This broke the updating of native base component.

relay on the master branch in dependency is super dangerous.

Thanks for this amazing package

**Comment by sankhadeeproy007** [comment]
@yoedfried Hi, I've just pushed a fix for the same to the theme repository.
Can you try reinstalling the dependencies and check again?

**Comment by mounthorse-slns** [comment]
@sankhadeeproy007 I'm experiencing the same issue. I've tried to reinstall all dependencies but the problem is still there.
Could you solve this?

**Comment by yoedfried** [comment]
Because there package not working with versioning, you should clear the app cache and then re install

**Comment by sankhadeeproy007** [comment]
Yes, we'll need to release a new version for the theme repo and then point to it in the package.json

**Comment by mounthorse-slns** [comment]
How can I clear cache to download the new version?

**Comment by yoedfried** [comment]
`npm start -- --reset-cache`

**Comment by mounthorse-slns** [comment]
@yoedfried @sankhadeeproy007 I've tried to reinstall all dependencies, run `npm cache clean`, run `npm start -- --reset-cache` but the problem still persit.
Am I missing something?

**Comment by Sebastian-Jedrocha** [comment]
I have faced the same issue with the Input component style but depending on the state instead of props. If the state changes Input styles stay the same. Might it be related to this bug?

**Comment by kenji4569** [comment]
I got the same issue. I think the problem persisting is due to package-lock.json in which native-base-shoutem-theme remains to be 0.2.3.

**Comment by krisnadiputra** [comment]
I am facing the same issue here....

**Comment by mounthorse-slns** [comment]
@sankhadeeproy007 when will you release the update?

**Comment by sankhadeeproy007** [comment]
In ~4 hours

**Comment by mounthorse-slns** [comment]
Thank you! Could you let us know when you've done?

**Comment by sankhadeeproy007** [comment]
Please check with 2.13.3

**Comment by mounthorse-slns** [comment]
@sankhadeeproy007 Yes! Now it works with `2.13.4'! Thank you very much!
