### ISSUE TITLE
Input On focus Bug

### ISSUE THREAD

**Issue by ismarosmanovic** [GeekyAnts/NativeBase#2882]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Setting focus on input controls throws following warning:
********************************************************
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, the componentWillUnmount method, 
    in ToastContainer (at connectStyle.js:392)
    in Styled(ToastContainer) (at Root.js:16)
    in RCTView (at View.js:45)
    in View (at Root.js:14)
    in Root (at connectStyle.js:392)
    in Styled(Root) (at App.js:62)

********************************************************

### node, npm, react-native, react and native-base version, expo version if used, xcode version
"expo": "^34.0.4",
"native-base": "^2.13.5",

### Steps to reproduce
I add Input control on the page then run it on both simulator and device and when the input gets focus warring is thrown.

My simple code is as follow:
***********************************
<Item regular error={this.state.UserNameError} style={{ width: '100%' }}>
                <Input ref={x => { this.InputUserName = x }} autoCorrect={false} placeholder='User Name' value={this.state.LoginUserName} onChangeText={(text) => {
                  this.setState({ LoginUserName: text });
                }} />
                {this.state.UserNameError &&
                  <Icon name='close-circle' />
                }
              </Item>
**********************************

### Is the bug present in both iOS and Android or in any one of them?
Both iOS and Android
### Any other additional info which would help us debug the issue quicker.
<img width="374" alt="Screenshot 2019-08-17 at 23 16 19" src="https://user-images.githubusercontent.com/45101366/63216885-1faf5800-c145-11e9-9937-a81ba45c80c3.png">
<img width="374" alt="Screenshot 2019-08-17 at 23 16 38" src="https://user-images.githubusercontent.com/45101366/63216886-2047ee80-c145-11e9-9726-f2935e5e969a.png">

**Comment by sankhadeeproy007** [comment]
Fixed in 2.13.8

**Comment by xfyre** [comment]
I can confirm that the issue is gone after upgrading to 2.13.8

**Comment by EdisonDevadoss** [comment]
I have still facing the same issue. Can anyone help me?
version:
"native-base": "^2.13.8",

**Comment by TheBlinkOfAnEye** [comment]
I am also having this issue when trying to implement the search bar functionality
    "expo": "^35.0.0",
    "expo-font": "~7.0.0",
    "native-base": "^2.13.8",
    "react": "16.8.3",

it appears to happen when the user first clicks in the <Input>.

Any help would be greatly appreciated. 

Thank you. 

```
  function SearchBar() {
    const memHandleClick = useCallback(event => {
      console.log(event);
    }, []);
    return (
      <Item>
        <Icon name='ios-search' />
        {didMount && (
          <Input
            placeholder='Search'
            onChangeText={event => memHandleClick(event)}
          />
        )}
      </Item>
    );
  };
```

```
<Header searchBar rounded>
    <SearchBar />
</Header>
```

**Comment by Vali06** [comment]
I'm still facing the issue although my App.tsx looks like your second update

**Comment by lucasklaassen** [comment]
https://github.com/GeekyAnts/NativeBase/issues/819#issuecomment-595847890

**Comment by Mavenic** [comment]
I can confirm this issue still exist on the  "native-base": "^2.13.12"
Even after having only one Root Component, the issue still exists.

**Comment by Aryk** [comment]
Any idea how to make Toast work if you use transparentModal from react navigation?

If you don't put ```<Root>``` inside the new transparentModal, the Toast will not show, but if you put it, I also get this error.

**Comment by koiralakiran1** [comment]
I'm also facing this issue on `"native-base": "^2.13.14"` even with just a single `<Root>`

"react": "16.13.1",
"react-native": "0.63.2",

**Comment by koiralakiran1** [comment]
The error for me was
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in ToastContainer (at connectStyle.js:392)
    in Styled(ToastContainer) (at Root.js:16)
    in RCTView (at View.js:34)
    in View (at Root.js:14)
    in Root (at connectStyle.js:392)
    in Styled(Root) (at WithToastRoot.tsx:9)
    in Unknown (at ComponentWrapper.js:42)
    in WrappedComponent (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

Looked into the code and I see this could be causing the issue https://github.com/GeekyAnts/NativeBase/blob/0315c117959bf19eae0f7c2a85e7faafa982f6e9/src/basic/ToastContainer.js#L60
```js
  componentDidMount() {
    Keyboard.addListener('keyboardDidShow', this.keyboardDidShow);
    Keyboard.addListener('keyboardDidHide', this.keyboardDidHide);
  }
```

The listeners are added here but never removed on `componentWillUnmount`. I tried doing the following on my local instance of the package and its working fine for me.
```js
  componentWillUnmount() {
    Keyboard.removeListener('keyboardDidShow', this.keyboardDidShow);
    Keyboard.removeListener('keyboardDidHide', this.keyboardDidHide);
  }
```

**Comment by koiralakiran1** [comment]
Update:
Saw there's already an existing PR with the above mentioned changes

https://github.com/GeekyAnts/NativeBase/pull/3233

**Comment by patrikrazem** [comment]
Has anyone had time to review this? I've been running into this same issue.

**Comment by koiralakiran1** [comment]
@patrikrazem The PR has already been merged. Not sure when it's coming up in the release.
