### ISSUE TITLE
DatePicker warning message

### ISSUE THREAD

**Issue by iranmarcius** [GeekyAnts/NativeBase#3020]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/

## Issue Description

React-native 0.61 started to use DateTimePicker from react-native-community, and both DatePickerAndroid / DatePickerIOS, witch are used by NativeBase DatePicker, were deprecated. It causes a warning message to be displayed everytime I use this component.

I would like to know if there are plans to update NativeBase to work with DateTimePicker from react-native-community or it there is a workaround this.

Thanks.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

node v10.16.2
yarn 1.19.2
react-native 0.61.4
react 16.9.0
native-base 2.13.8
expo 3.11.1

**Comment by alejandrosobko** [comment]
Same issue here. Any fix?

**Comment by shystruk** [comment]
+1

**Comment by tudiantuan** [comment]
+1

**Comment by ShutoYamada** [comment]
+1

**Comment by maxi-brochon-exa** [comment]
+1

**Comment by diegolaciar** [comment]
+1  , with nativebase 2.13.8

**Comment by alteyss** [comment]
+1

**Comment by EduardoUstarez** [comment]
+1 with nativebase 2.13.8

**Comment by Grantlyk** [comment]
This is something that i'm also getting an error message for too, i'm more than happy to open a PR if anyone wants it

**Comment by Relax594** [comment]
> 
> 
> This is something that i'm also getting an error message for too, i'm more than happy to open a PR if anyone wants it

Yes please!

**Comment by suhailaleryani** [comment]
+1

**Comment by Manu206** [comment]
+1

**Comment by shystruk** [comment]
I switched to https://github.com/mmazzarolo/react-native-modal-datetime-picker fits perfectly to my needs

**Comment by JeffHooper** [comment]
+1

**Comment by hanykumar** [comment]
Hi @Grantlyk , we will appreciate if you create PR for that. Thanks

**Comment by alexandrtovmach** [comment]
PR with fix https://github.com/GeekyAnts/NativeBase/pull/3250
@hanykumar could you take a look?

**Comment by hanykumar** [comment]
Hi @alexandrtovmach , We will merge it soon. Thanks for this working PR.

**Comment by Relax594** [comment]
@hanykumar Please merge asap. The old (current) version is broken on iOS 14.

**Comment by krisidmisso** [comment]
@hanykumar can you please merge this? https://github.com/GeekyAnts/NativeBase/pull/3251

**Comment by alexandrtovmach** [comment]
Ping

**Comment by tyhour** [comment]
use this package, (yarn add https://github.com/tyhour/NativeBase.git) I just fixed some issue and all warning with Native Base. Also fixed error (this.requestAnimationFrame is not a function appears). I wish this can help you. :)

**Comment by alexandrtovmach** [comment]
Don't use it https://github.com/GeekyAnts/NativeBase/issues/3020#issuecomment-738008902, because https://github.com/GeekyAnts/NativeBase/pull/3250 already merged and released

**Comment by alexandrtovmach** [comment]
This issue should be closed, because issue fixed in v2.13.15+

**Comment by tyhour** [comment]
> Don't use it [#3020 (comment)](https://github.com/GeekyAnts/NativeBase/issues/3020#issuecomment-738008902), because #3250 already merged and released

==========
Hi sir new version has been release but why they not fixed another error with Tab of Native Base (TypeError: this.requestAnimationFrame is not a function. (In 'this.requestAnimationFrame(function () {
        _this5.goToPage(_this5.state.currentPage);
      })', 'this.requestAnimationFrame' is undefined)) ?

**Comment by alexandrtovmach** [comment]
@tyhour 
1. It's separate issue, and not related to DatePicker updates
2. Instead of recommending using your fork, better to create PR to original repo

**Comment by tyhour** [comment]
> @tyhour
> 
> 1. It's separate issue, and not related to DatePicker updates
> 2. Instead of recommending using your fork, better to create PR to original repo

Ok thanks I think they will update soon.

**Comment by alexandrtovmach** [comment]
Fixed in [`v2.15.0`](https://www.npmjs.com/package/native-base/v/2.15.0)
