### ISSUE TITLE
Fontisto Icon missing

### ISSUE THREAD

**Issue by rmkpatchaa** [GeekyAnts/NativeBase#3063]
- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Fontisto is not included in icons. Font file is present and linked but IconNB is not importing it.
https://github.com/GeekyAnts/NativeBase/blob/3924fa6b901b5d3cc315be64ffe11a9b8392556e/src/basic/IconNB.js

I get this error : 
```
Warning: Failed prop type: Invalid prop `type` of value `Fontisto` supplied to `IconNB`, expected one of ["AntDesign","Entypo","EvilIcons","Feather","FontAwesome","FontAwesome5","Foundation","Ionicons","MaterialCommunityIcons","MaterialIcons","Octicons","SimpleLineIcons","Zocial"]
```

**Comment by hanykumar** [comment]
Hi @rmkpatchaa , we have fixed this issue and it is available on master branch now. 
Thanks

**Comment by hanykumar** [comment]
Hi @rmkpatchaa , latest version of Native base has been released. The issues should be fixed now.
[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)

**Comment by amar1n** [comment]
Hi, I have the same issue with...
- native-base: 2.13.12
- react-native: sdk-35.0.0

Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules/native-base/dist/src/basic/IconNB.js"

Maybe I missed something or the issue is not resolved at all.

[Here](https://github.com/expo/vector-icons/issues/112) you can see more people with the same problem

Thanks in advandce!

**Comment by mrkpatchaa** [comment]
I've tested the new version and icons are showing but i'm still getting the warning. But now Icons are showing.

**Comment by amar1n** [comment]
Every works fine with native-base: 2.13.7, 2.13.8

The problem appears in version **^**2.13.8 and remains until 2.13.12

Unable to resolve module `@expo/vector-icons/Fontisto` from `/Users/alberto/Documents/TALLER/elCatalejo/node_modules/native-base/dist/src/basic/IconNB.js`: Module `@expo/vector-icons/Fontisto` does not exist in the Haste module map

**Comment by amar1n** [comment]
In short, what you need to install is the exact 2.13.8 version

`npm i --save-exact native-base@2.13.8`

**Comment by sankhadeeproy007** [comment]
Yes, until expo upgrades to add fontisto, using `2.13.8` seems to be the best bet.
