### ISSUE TITLE
Cannot find module 'react/lib/ReactNativePropRegistry' from ...

### ISSUE THREAD

**Issue by msom** [GeekyAnts/NativeBase#319]
...
- computeProps.js
- Button.js

with react `15.4.1`

`var ReactNativePropRegistry = require('ReactNativePropRegistry');` seems to work

**Comment by tanmynguyen** [comment]
hjc. Me too. so I use react 15.3.2. Admin @nativebase please fix it. Thanks

**Comment by tanmynguyen** [comment]
I using native-base: 0.5.15

**Comment by jasonbahl** [comment]
+1

**Comment by jaisonveneri** [comment]
+1

**Comment by Deepankar01** [comment]
+1

**Comment by matthieugayon** [comment]
+1

**Comment by helloncanella** [comment]
+1

**Comment by ujwal-setlur** [comment]
+1

**Comment by ottoo** [comment]
+1

**Comment by ujwal-setlur** [comment]
Replacing with 

import ReactNativePropRegistry from 'react-native/Libraries/Renderer/src/renderers/native/ReactNativePropRegistry';

worked, but ReactNativePropRegistry is an internal API, I believe, and not public. Can this call be replaced with a public API?

Can this be resolved quickly please?

**Comment by ujwal-setlur** [comment]
Actually, the following work:

import { ReactNativePropRegistry } from 'react-native';

OR

var ReactNativePropRegistry = require{'react-native'};

So, it seems that ReactNative is indeed publicly exposed now, but it should not be referenced with an absolute path.

This needs to be fixed in:

- NativeBase
Button.js
computeProps.js

- react-native-easy-grid
computeProps.js

**Comment by ujwal-setlur** [comment]
I have created a pull request for this.

**Comment by ujwal-setlur** [comment]
Sorry, my comment earlier was wrong. The explicit path still has to be specified. I saw that being checked in.

**Comment by streamlesswaveson** [comment]
+1

**Comment by dharness** [comment]
I encountered this error, but it seems to have stuck around even after removing native-base?

I even tried using `react-native init <new project>` to create an entirely new project -- but the error persists? Any insight on why this might be?

The path the error is referencing doens't even exist..

![](https://puu.sh/sx2qq/8c7228c6f8.png)

**Comment by sankhadeeproy007** [comment]
Fixed with v0.5.16

**Comment by tzyhhaur** [comment]
Seems that error still persist. However, the issue is with the package react-native-easy-grid. It has to be updated as well.

**Comment by ujwal-setlur** [comment]
Correct. That has to be updated as well and the dependency in native-base has to updated. 


Get Outlook for iOS




On Mon, Nov 28, 2016 at 5:10 AM -0800, "tzyhhaur" <notifications@github.com> wrote:












Seems that error still persist. However, the issue is with the package react-native-easy-grid. It has to be updated as well.

**Comment by SupriyaKalghatgi** [comment]
Fixed with latest release [0.5.18](https://github.com/GeekyAnts/NativeBase/releases/tag/v0.5.18)

**Comment by thundenilla** [comment]
getting the same error message but im not even using 'ReactNativePropRegistry'

**Comment by SupriyaKalghatgi** [comment]
@thundenilla Are you on NB 0.5.18?
Also if you have `Easy-Grid` in your `package.json` make sure it is **0.1.7**

**Comment by yukkeechang** [comment]
@dharness did you ever figure out why that happens?
This error kept happening to me and all i do is change the path everytime but its getting really annoying. 
And for native base I'm at "native-base": "^2.1.5",

**Comment by dharness** [comment]
@yukkeechang no I did not, I ended up not using React Native at all.

**Comment by ujwal-setlur** [comment]
@yukkeechang, here is the combination that works for me: 

* react-native 0.46.3
* native-base 2.2.1
* react-native-easy-grid 0.1.14

Unfortunately, native-base and react-native-easy-grid depends on react-native internals, and only specific version combinations work. 

@dharness, which framework did you end up using?
