### ISSUE TITLE
Toast does not close on button press

### ISSUE THREAD

**Issue by blakehoffman** [GeekyAnts/NativeBase#3261]
Native base toast does not dismiss on button press.

node version - 14.5,
npm version - 6.14.8
react-native version - 0.62.2
react-antive-cli version - 2.0.1 
react version - 6.14.8
native-base version - 6.14.8

When tapping on close button within the toast component, it should disappear.

Toast does not close when tapping on close button.  It only goes away after specified display time (3 seconds).

The following code snippet is the function that is called from all of my screens to show the toast component.  It is wrapped in the Root component at the top level.
```
import { Toast } from 'native-base';
import Colors from '../constants/Colors';

export function showErrorToast(message: string) {
  Toast.show({
    text: message,
    buttonText: 'Okay',
    duration: 3000,
    style: {
      backgroundColor: Colors.red
    }
  });
}
```

I am running this on a pixel 4.  It works fine on an ios emulator.

**Comment by hanykumar** [comment]
Hi @blakehoffman , it works fine on pixel3a. Can you provide minimal code reproduction on **Expo snack** for the same?

**Comment by blakehoffman** [comment]
Hey @hanykumar , it seems I can't reproduce it within a snack.  Sadly it only happens when I run it on my pixel 4.

**Comment by hanykumar** [comment]
Hi @blakehoffman , there is no virtual device for pixel 4 yet, so we are unable to test it.

**Comment by WolfyUK** [comment]
We have also experienced this issue, but only on Huawei devices. It started occurring after upgrading to RN 0.62.2 and seems to be related to the Toast swipe functionality. It also exists with RN 0.63.3. 

I have a PR I'm about to link that allows the swipe-to-dismiss to be disabled via a new config value, which was fine as a resolution to this issue in our case.

**Comment by dellert** [comment]
+ still does not working at built apk on device

**Comment by shivrajkumar** [comment]
@dellert Fixed in the latest version with the PR from @WolfyUK

**Comment by Kolyunya** [comment]
@shivrajkumar I believe this issue is still not *really fixed* in `2.15.2`. There definitely is some problem related to the swipe-to-close mechanism. The button would not close the toast when the swipe in enabled. It is reproducing in 100% of times on real devices but I wasn't able to reproduce it on an emulator in expo yet.

The `swipeDisabled: true` is obviously just a hack. If you decide that two features: swiping and button are mutually exclusive then one of two options should apply:
1. Either the button must not be rendered at all when the swiping is enabled.
2. Or the swiping must be disabled when the button is rendered.

If you decide to introduce this limitation, then it also should be documented.
