### ISSUE TITLE
Icons broken - auto-linking issue? - react-native 0.63.2

### ISSUE THREAD

**Issue by fosteruk** [GeekyAnts/NativeBase#3262]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

A recent update to Xcode introduced an issue in ReactNative causing images to not render. This was patched in React-Native. In order to get my project working again I had to upgrade my version of react-native (0.63.2). In doing that I have found that NativeBase auto-linking appears to be broken.  I get error **Unrecognized font family 'Ionicons**' when running my app in the iOS simulator. Which tells me the fonts were not linked correctly. Icons are also broken on Android but there is no error message.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

Node v12.18.2
Npm 6.14.8
react-native 0.63.2
react 16.13.1
native-base 2.13.14
xcode 12.0.1

#### Expected behaviour

Installing native base should auto link Icon fonts.

#### Actual behaviour

Errors related to missing fonts which indicates broken auto link functionality.

#### Steps to reproduce

Setup fresh react-native environment with latest react-native and latest native-base.

#### Is the bug present in both iOS and Android or in any one of them?

The error appears on iOS only but icons are also broken on Android which makes me think the same issues is affecting both iOS and android.

**Comment by akontaroudis** [comment]
After upgrading to react-native 0.63.2 I've also noticed that icons are broken. I've created an example repo with a new RN project. As you can see in the screenshota below as well as in the example repo icons in iOS and Android are displaying the wrong icons.

The icons in the screenshots are:

```
<Icon name="arrow-forward" />
<Icon name="arrow-back" />
<Icon name="home" />
```

<img width="520" alt="broken_icons" src="https://user-images.githubusercontent.com/27508555/94358783-eec18680-00ab-11eb-910a-613bb63e6bf5.png">
<img width="518" alt="broken_icons_android" src="https://user-images.githubusercontent.com/27508555/94358785-f2eda400-00ab-11eb-8daa-941a071f7c64.png">

Example repo is https://github.com/akontaroudis/NativeBaseBrokenIcons

native-base version is 2.13.14

**Comment by jahead** [comment]
We are seeing this too. 
#3194 which while closed, only solved in for android, but not really. 
```
rm android/app/src/main/assets/fonts/*.ttf
cp ./node_modules/react-native-vector-icons/Fonts/*.ttf android/app/src/main/assets/fonts/
```
should not be the solution. 
As far as I can tell it's due to the vector-icons and native base having different fronts in their folders... but there's some noise around this. 

#3216 is a PR that is meant to fix this. but has been moved.

#3161 @hanykumar has said that running through the manual linking of the fonts may solve the problem, but this should all be handled by latest version of autolinking, which doesn't require any developer input.

**Comment by jahead** [comment]
Okay, while I haven't tested this for android if you `yarn add react-native-vector-icons` and do a `pod install` you should see it fixed

If you've manually added the fonts prior, you will need to remove them from the build phase as now vector icons will autolink the fonts into your project. see https://github.com/oblador/react-native-vector-icons/issues/1225

@fosteruk can you see if this works for you too?

I think if native base is going to let vector maintain the fonts then this is much better solution. As it auto links automatically, at least for ios.

**Comment by fosteruk** [comment]
@jahead I just tried but it doesn't fix it for me. Still getting an error on iOS and the icons are not displaying in either iOS or Android.

**Comment by Dheyson** [comment]
Here got the same native base issue. In my case, was trying to use the radio button, but seems that doesn't show well on android also.

**Comment by haserta98** [comment]
i have the same issue

**Comment by sefamertkaya** [comment]
Same problem

**Comment by fosteruk** [comment]
@jahead I managed to get it working by installing react-native-vector-icons and then manually adding it to my ios/Podfile and also manually editing Info.plist to reference Ionicons.ttf. I have not tested it on Android yet but I imagine manual linking would be required for that also.

While it is possible to get it working. This linking step should be dealt with automatically. This still needs to be fixed.

**Comment by asyam1** [comment]
I tried to link all the font files from the react-native-vector-icons into projects Build Phases in Xcode and it worked for me. And for android, I deleted all the fonts under android/app/src/main/assets/fonts and re-added them. 

<img width="1486" alt="Screen Shot 2020-10-07 at 10 41 28 AM" src="https://user-images.githubusercontent.com/28627691/95346736-25f11e00-088a-11eb-8230-d12dd28a50c3.png">

Hope this helps

**Comment by jahead** [comment]
@fosteruk Hey thanks for adding that extra step! I wasn't working from a completely clean environment. 

@asyam1 Yep, it seems you have to follow the vector icons install guide to link the assets for ios and android. 
https://github.com/oblador/react-native-vector-icons#option-with-gradle-recommended

If you don't want to copy the assets you can follow the above guide have gradle automatically copy the assets at build time. Which will mean you shouldn't see this out of date error in the future. 

I think the documentation should reflect this step more explicitly. It also be nice to get some feedback from the maintainers on this issue, I'm happy to do a PR if the work aligns to their goals.

@Dheyson @sefamertkaya @haserta98 Are you still having issues, after following the comments here?

**Comment by piccinnigius** [comment]
@jahead thanks so much for right solution!!

**Comment by InfoAndroid** [comment]
I am facing same issue RN:0.63.3 Xcode : 12.0.1

![Simulator Screen Shot - iPhone 11 - 2020-11-02 at 16 11 34](https://user-images.githubusercontent.com/21953527/97859075-15678280-1d26-11eb-9940-9acf39ec6a4a.png)

**Comment by jahead** [comment]
Did you follow the instructions on installing react-native-vector-icons?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by melvinchng** [comment]
Having the same issue with Android (not tested on iOS) but with Native Base 2.13.14 React Native 0.62.2. Have everything setup correctly for the react-native-vector-icons.

**Comment by InfoAndroid** [comment]
> Did you follow the instructions on installing react-native-vector-icons? Get Outlook for Android<https://aka.ms/ghei36>
> […](#)



> I am facing same issue RN:0.63.3 Xcode : 12.0.1
> 
> ![Simulator Screen Shot - iPhone 11 - 2020-11-02 at 16 11 34](https://user-images.githubusercontent.com/21953527/97859075-15678280-1d26-11eb-9940-9acf39ec6a4a.png)



> I am facing same issue RN:0.63.3 Xcode : 12.0.1
> 
> ![Simulator Screen Shot - iPhone 11 - 2020-11-02 at 16 11 34](https://user-images.githubusercontent.com/21953527/97859075-15678280-1d26-11eb-9940-9acf39ec6a4a.png)

The issue has been resolved now
just Add react-native-vector-icons fonts in plist

**Comment by asrudii** [comment]
same problem bro

**Comment by arled** [comment]
This is rubish

**Comment by Yarkhan** [comment]
Found an easy way to fix it on both iOS and Android.
For android on `android/app/build.gradle`
```
apply from: "../../node_modules/react-native/react.gradle" 
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle" // <= this line, needed for vector-icons
```

For iOS on `ios/Podfile`
```
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'  # <= this line, needed for vector-icons
```

rebuild and reinstall, icons should display properly.

As for the reason this happens, react-native-vector-icons library doesn't properly link on newer react native versions. Using Gradle and Cocoapods ensure the files needed are in sync. See the following sections in their readme

https://github.com/oblador/react-native-vector-icons#option-with-gradle-recommended
https://github.com/oblador/react-native-vector-icons#option-with-cocoapods
