### ISSUE TITLE
Using Radio buttons causes aria warning

### ISSUE THREAD

**Issue by btrewern** [GeekyAnts/NativeBase#3947]
Any use of Radio buttons causes the following warning:

**If you do not provide children, you must specify an aria-label for accessibility.**
**at node_modules/@react-native-aria/radio/src/useRadio.ts:43:4 in useRadio**
**at node_modules/native-base/src/components/primitives/Radio/Radio.tsx:35:25 in Radio**

I'm using the following:
Expo 4.10.0
native-base 3.0.7 

Happens on either ios or android clients.

**Comment by intergalacticspacehighway** [comment]
@btrewern can you please share the code snippet that's causing this warning?

**Comment by btrewern** [comment]
Hi, I've just created a new blank app with expo and just copied and pasted the first example from here: https://docs.nativebase.io/radio

I am using the following:

node.js - v14.17.2
expo-cli - 4.10.0
expo - 42.0.1
native-base - 3.0.7

I get the following warning:

If you do not provide children, you must specify an aria-label for accessibility
at node_modules/@react-native-aria/radio/src/useRadio.ts:42:7 in useRadio
at http://172.16.0.100:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:176951:41 in Radio
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:6 in Refresh.performReactRefresh

TIA

Ben

**Comment by btrewern** [comment]
Also it seems using just a few radio button on a screen slows it down quite noticeably, to the point that it becomes unusable.

**Comment by intergalacticspacehighway** [comment]
@btrewern this has been resolved in 3.1. Let me know if it doesn't work, I'll reopen the issue.

**Comment by arunim2405** [comment]
@intergalacticspacehighway still getting this warning when using Checkbox Group, using version 3.1.0

**Comment by Southclaws** [comment]
Using 3.3.2 and seeing this on every render, fills the log up with a useless stack trace. I don't mind these errors but please don't log a stack trace because it does not help debugging since it's either internal transpiled nonsense or just elements like `Box`

![image](https://user-images.githubusercontent.com/1636971/151381600-5d7d9e08-ca9b-4725-b971-a60ba44c7a35.png)

**Comment by AlixH** [comment]
I am still seeing the warning for the checbox at every render, with version 3.4.13

**Comment by hotaryuzaki** [comment]
just add accessibilityLabel props to solved this issue
