### ISSUE TITLE
Stack doesn't inject spacing in items inside of a fragment

### ISSUE THREAD

**Issue by cmaycumber** [GeekyAnts/NativeBase#3972]
I'm not sure if this is intended behavior but when leveraging something similar to the following code, the stack doesn't inject spacing between the items inside a fragment: 

```jsx
<Stack space="md">
  <Item/>
  <>
   // No Space rendered between these elements
   <Item/> 
   <Item/> 
 </>
</Stack>
```

Expected behavior: 

Stack injects spacing between the elements inside of a fragment

**Comment by intergalacticspacehighway** [comment]
Hi @cmaycumber Currently stack behaves this way.
```jsx
<Stack space="md">
  <Item/>
  <Item/> 
  <Item/> 
</Stack>
```
will be converted to
```jsx
<Box>
  <Item/>
  <Box height="md" />
  <Item/>
  <Box height="md" />
  <Item/> 
</Box>
```

i.e. It adds Spacer element in between. So, in your code it'll be converted to
```jsx
<Stack space="md">
  <Item/>
  <Box height="md" />
  <>
   <Item/> 
   <Item/> 
  </>
</Stack>
```

i.e. no spacing will be added. How common is this use case and is it possible for you to not use fragments inside Stack? 
Let us know. Thanks!

**Comment by cmaycumber** [comment]
So far this is the first time I’ve ran into it, to get around it I’m just
applying margin to one of the items in the fragment.

Right now the items are being rendered conditionally, I could break them
out and render them separately but this would duplicate a lot of logic.

This definitely seems like a very one off scenario, bc I’m also using flex
to make the items equally 1/3 in size, so wrapping them in another
component isn’t really an option.

If this is intended behavior I’ll close the issue because there are
workarounds. I just thought I’d make it known.

**Comment by surajahmed** [comment]
@cmaycumber This issue has been fixed in version `3.3.6`. Thanks for reporting!

**Comment by Jokerwolf** [comment]
Hey everyone, not sure if i understand it correctly, but the original issue seems to be not fixed.
_space_ does not propagate to Fragment's children. Could you please state if this is an intended behavior? 

https://snack.expo.dev/@jokerwolf/nativebase-playground
