### ISSUE TITLE
Require Cycles Warning

### ISSUE THREAD

**Issue by fervailanti** [GeekyAnts/NativeBase#4293]
Some circular requiring are causing this warning to appear:

<img width="1003" alt="Captura de pantalla 2021-11-10 a las 21 36 33" src="https://user-images.githubusercontent.com/54537095/141193718-d454806a-70b2-47ec-95c5-ef87ef64810c.png">

This is related to the way this components are importing another components. 

Specifically, the files causing this are:

- `src/components/composites/Breadcrumb/Breadcrumb.tsx`
- `src/components/primitives/Checkbox/SizedIcon.tsx`

**Comment by fervailanti** [comment]
I made a PR with the fix here: **https://github.com/GeekyAnts/NativeBase/pull/4292**.

**Comment by ankit-tailor** [comment]
Hi @fervailanti , We'll look into this. Thanks for reporting.

**Comment by hadils** [comment]
Version 3.3.5 has these cycle warnings:

```backend.js:2170 Require cycle: node_modules/@aws-amplify/core/lib-esm/index.js -> node_modules/@aws-amplify/core/lib-esm/Providers/index.js -> node_modules/@aws-amplify/core/lib-esm/Providers/AWSCloudWatchProvider.js -> node_modules/@aws-amplify/core/lib-esm/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
overrideMethod @ backend.js:2170
metroRequire @ require.js:117
(anonymous) @ AWSCloudWatchProvider.js:70
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:1
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:24
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:13
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
$CLJS.shadow$js.aws-amplify @ index.js:1481
$CLJS.shadow$jsRequire @ index.js:1459
global.require @ index.js:1469
eval @ shadow.js.shim.module$aws_amplify.js? [sm]:3
goog.globalEval @ index.js:489
env.evalLoad @ index.js:1445
(anonymous) @ index.js:1718
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:201
metroRequire @ require.js:128
(anonymous) @ index.bundle?platform=ios&dev=true&hot=false&minify=false:671674
executeApplicationScript @ debuggerWorker.aca173c4.js:4
(anonymous) @ debuggerWorker.aca173c4.js:4
backend.js:2170 Require cycle: node_modules/@aws-crypto/crc32/build/index.js -> node_modules/@aws-crypto/crc32/build/aws_crc32.js -> node_modules/@aws-crypto/crc32/build/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
overrideMethod @ backend.js:2170
metroRequire @ require.js:117
(anonymous) @ aws_crc32.js:8
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:106
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ EventStreamMarshaller.js:4
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:4
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ EventStreamMarshaller.js:4
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ provider.js:4
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:4
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ runtimeConfig.browser.js:7
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ runtimeConfig.native.js:6
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ KinesisClient.js:4
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:4
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ AWSKinesisProvider.js:50
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:2
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:19
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:22
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
$CLJS.shadow$js.aws-amplify @ index.js:1481
$CLJS.shadow$jsRequire @ index.js:1459
global.require @ index.js:1469
eval @ shadow.js.shim.module$aws_amplify.js? [sm]:3
goog.globalEval @ index.js:489
env.evalLoad @ index.js:1445
(anonymous) @ index.js:1718
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:201
metroRequire @ require.js:128
(anonymous) @ index.bundle?platform=ios&dev=true&hot=false&minify=false:671674
executeApplicationScript @ debuggerWorker.aca173c4.js:4
(anonymous) @ debuggerWorker.aca173c4.js:4
Show 45 more frames
backend.js:2170 Require cycle: node_modules/@aws-amplify/pubsub/lib-esm/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/PubSub.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js -> node_modules/@aws-amplify/pubsub/lib-esm/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
overrideMethod @ backend.js:2170
metroRequire @ require.js:117
(anonymous) @ AWSAppSyncRealTimeProvider.js:98
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:15
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ PubSub.js:52
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:13
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ GraphQLAPI.js:89
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:13
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ API.js:63
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:13
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:25
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
$CLJS.shadow$js.aws-amplify @ index.js:1481
$CLJS.shadow$jsRequire @ index.js:1459
global.require @ index.js:1469
eval @ shadow.js.shim.module$aws_amplify.js? [sm]:3
goog.globalEval @ index.js:489
env.evalLoad @ index.js:1445
(anonymous) @ index.js:1718
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:201
metroRequire @ require.js:128
(anonymous) @ index.bundle?platform=ios&dev=true&hot=false&minify=false:671674
executeApplicationScript @ debuggerWorker.aca173c4.js:4
(anonymous) @ debuggerWorker.aca173c4.js:4
Show 21 more frames
backend.js:2170 Require cycle: node_modules/@aws-amplify/datastore/lib-esm/types.js -> node_modules/@aws-amplify/datastore/lib-esm/util.js -> node_modules/@aws-amplify/datastore/lib-esm/types.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
overrideMethod @ backend.js:2170
metroRequire @ require.js:117
(anonymous) @ util.js:71
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ types.js:37
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ multiAuthStrategy.js:59
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:2
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ datastore.js:94
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:1
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:26
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
$CLJS.shadow$js.aws-amplify @ index.js:1481
$CLJS.shadow$jsRequire @ index.js:1459
global.require @ index.js:1469
eval @ shadow.js.shim.module$aws_amplify.js? [sm]:3
goog.globalEval @ index.js:489
env.evalLoad @ index.js:1445
(anonymous) @ index.js:1718
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:201
metroRequire @ require.js:128
(anonymous) @ index.bundle?platform=ios&dev=true&hot=false&minify=false:671674
executeApplicationScript @ debuggerWorker.aca173c4.js:4
(anonymous) @ debuggerWorker.aca173c4.js:4
Show 13 more frames
backend.js:2170 Require cycle: node_modules/aws-amplify/lib-esm/index.js -> node_modules/aws-amplify/lib-esm/withSSRContext.js -> node_modules/aws-amplify/lib-esm/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
overrideMethod @ backend.js:2170
metroRequire @ require.js:117
(anonymous) @ withSSRContext.js:17
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.js:34
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
$CLJS.shadow$js.aws-amplify @ index.js:1481
$CLJS.shadow$jsRequire @ index.js:1459
global.require @ index.js:1469
eval @ shadow.js.shim.module$aws_amplify.js? [sm]:3
goog.globalEval @ index.js:489
env.evalLoad @ index.js:1445
(anonymous) @ index.js:1718
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:201
metroRequire @ require.js:128
(anonymous) @ index.bundle?platform=ios&dev=true&hot=false&minify=false:671674
executeApplicationScript @ debuggerWorker.aca173c4.js:4
(anonymous) @ debuggerWorker.aca173c4.js:4
backend.js:2170 Require cycle: node_modules/native-base/src/components/primitives/index.ts -> node_modules/native-base/src/components/primitives/Checkbox/index.tsx -> node_modules/native-base/src/components/primitives/Checkbox/Checkbox.tsx -> node_modules/native-base/src/components/primitives/Checkbox/SizedIcon.tsx -> node_modules/native-base/src/components/primitives/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
overrideMethod @ backend.js:2170
registerWarning @ LogBox.js:118
warnImpl @ LogBox.js:64
console.warn @ LogBox.js:37
metroRequire @ require.js:117
(anonymous) @ SizedIcon.tsx:2
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ Checkbox.tsx:20
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.tsx:1
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.ts:12
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ AlertIcon.tsx:2
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.tsx:1
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.ts:13
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
(anonymous) @ index.tsx:1
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:210
metroRequire @ require.js:128
$CLJS.shadow$js.native-base @ index.js:1484
$CLJS.shadow$jsRequire @ index.js:1459
global.require @ index.js:1469
eval @ shadow.js.shim.module$native_base.js? [sm]:3
goog.globalEval @ index.js:489
env.evalLoad @ index.js:1445
(anonymous) @ index.js:1734
loadModuleImplementation @ require.js:349
guardedLoadModule @ require.js:201
metroRequire @ require.js:128
(anonymous) @ index.bundle?platform=ios&dev=true&hot=false&minify=false:671674
executeApplicationScript @ debuggerWorker.aca173c4.js:4
(anonymous) @ debuggerWorker.aca173c4.js:4
Show 20 more frames
backend.js:2170 Require cycle: node_modules/native-base/src/components/primitives/index.ts -> node_modules/native-base/src/components/primitives/Select/index.tsx -> node_modules/native-base/src/components/primitives/Select/SelectItem.tsx -> node_modules/native-base/src/components/composites/Actionsheet/index.tsx -> node_modules/native-base/src/components/composites/Actionsheet/Actionsheet.tsx -> node_modules/native-base/src/components/composites/Modal/index.tsx -> node_modules/native-base/src/components/composites/Modal/Modal.tsx -> node_modules/native-base/src/components/composites/Transitions/index.tsx -> node_modules/native-base/src/components/composites/Transitions/Slide.tsx -> node_modules/native-base/src/components/primitives/index.ts
```

**Comment by surajahmed** [comment]
This issue is fixed in version `3.3.6`. Thanks for reporting!

**Comment by maaliHasan** [comment]
@surajahmed Im using native-base version 3.4.22 and I still encounter this issue !!?

**Comment by OguzEkinci** [comment]
> This issue is fixed in version `3.3.6`. Thanks for reporting!

when will you upgrade  ?
