### ISSUE TITLE
Search Bar without button (full width)

### ISSUE THREAD

**Issue by joinjoohny** [GeekyAnts/NativeBase#463]
How to make search bar, the full width of header without button search.
`      <Button transparent>
          Search
      </Button>` 
If I remove the button search, search bar displayed incorrectly.

<img width="371" alt="rns" src="https://cloud.githubusercontent.com/assets/1760643/22600552/b929908a-ea43-11e6-87f9-afd540d216f2.png">

`"react-native": "0.35.0"`
`"native-base": "0.5.11"`

Thx.

**Comment by manfredxu99** [comment]
+1

**Comment by bgdavidx** [comment]
+2

**Comment by GeekRishabh** [comment]
@manfredxu99 @bgdavidx @joinjoohny you guys can try 
```
<Button transparent style={{ borderWidth: 0.4}}>
    <Icon name="ios-search" />
          <Input placeholder="Search"  />
          <Icon name="ios-people" />
</Button>
```
the above will work for you .

**Comment by nixalite** [comment]
not working for me too. Same issue. 
"native-base": "^2.1.1",
 "react-native": "0.43.2",

**Comment by GeekRishabh** [comment]
@nixalite if you have ejected NB theme, you need to merge it with the new theme as the older theme doesn't have input component  theme . you can add  [input.js](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Input.js) in your ejected theme and include it  in theme index.js [this way](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/index.js#L77)

**Comment by shivrajkumar** [comment]
Closing the issue as the above should resolve the issue in v2.x
Let me know if it doesn't

**Comment by sangampokharel** [comment]
<Header style={styles.header}   >
            <Left style={{flex:1}}>
                <Icon 
                name="camera"
                style={{color:'#fff'}}
                />
            </Left>

          <Body style={{flex:5}}>
             <Item >
             <Icon name="search"  style={{color:'#fff'}} />
             <Input placeholder="Search Items Here..."  placeholderTextColor="#fff" style={{width:300}}/>
             <Icon name="people"  style={{color:'#fff'}} />
           </Item>
          </Body>
          <Right style={{flex:1}}>
                <Icon name="home"  style={{color:'#fff'}}/>
              </Right>
        </Header>

**Comment by Moumit** [comment]
Still not no option on this .. can you please guide or re-open the issue
