### ISSUE TITLE
rightElement in Input requires 2 clicks to trigger onClick action

### ISSUE THREAD

**Issue by kpbochenek** [GeekyAnts/NativeBase#4720]
### Description

When IconButton with onClick action is in Input rightElement section, it requires 2 clicks to trigger onClick action for this component

### CodeSandbox/Snack link

https://docs.nativebase.io/input#h3-password-input

### Steps to reproduce

1. go to 'https://docs.nativebase.io/input#h3-password-input'
2. Click on InputText area
3. Click on 'Show' button (nothing happens)
4. Click on 'Show' button - it changes to 'Hide' and handler for onClick is triggered

Expected:
Step 3 should change text to 'Hide' and trigger action

### NativeBase Version

3.3.x

### Platform
(did not check others, only confirmed with Expo)
- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

When you click twice on Icon then clicking again requires just 1 click, it looks like when you are focused on input area then first click is to just get focus to IconButton and then clicking again fires proper action.

**Comment by mayank-96** [comment]
Hello @kpbochenek, Thanks for reporting this issue, we'll fix it soon.

**Comment by RobertDS07** [comment]
I tried to solve it, but I can't, in next some things that I can see with my try:

1. The problem is only in web
2. The problem occurs when the 'isFocused' state of 'Input' changes
3. The 'InputRightElement' is returned of a function 'usePropsResolution' and this component is returning a while times, I guess that problem can stay here, the component return when onBlur is called clicking in 'InputRightElement' and it is rendering again, causing the error of onClick

I hope I could have helped :D

**Comment by zhumingcheng697** [comment]
I’m running into the same issue on web. I have tried a few different kinds of “buttons” and none of them is working 100% as expected. Some of them is even never responding to clicks at all. However, focusing the button using the tab key and pressing the enter key always fire `onPress`. Also, for all NativeBase components that support `isPressed` and `isFocused` props for render props or `_pressed` and `_focus` pseudo props, these props are being updated/applied as expected on the **second** and subsequent clicks (assuming `onPress` did not fire on the first click), and `isHovered` and `_hover` is always working 100% as expected. Some slight differences below:

1. `onPress` of NativeBase `Pressable` is **never** fired **no matter how many times I click it**. Clicking it 2+ times in a roll has no effect. Even if the `Input` did not have the focus before the first click, clicks are never registered.

2. NativeBase `IconButton`can have different behaviors depending on whether the `_pressed`, `_hover`, and `_focus` pseudo prop have a nested `_icon` pseudo prop set:
    1. If the `_focus` prop is set with a nested `_icon` pseudo prop, then (regardless of whether `_pressed` or `_hover` is set  with a nested `_icon` pseudo prop), the `IconButton` fires `onPress` on the **third** click if the `Input` had the focus before the first click, and `onPress` is fired on the **second** click if the `Input` did not have the focus before the first click. 
    2. If the `_focus` and the `_hover` pseudo props are **not** set with a nested `_icon` pseudo prop, but the `_pressed` pseudo prop **is** set with a nested `_icon` pseudo prop, the `IconButton` never fires `onPress` regardless of whether `Input` had the focus before the first click. Similar to situation 1 with `Pressable`.
    3. If the `_focus` pseudo prop is **not** set with a nested `_icon` pseudo prop, but the `_hover` pseudo prop **is** set with a nested `_icon` pseudo prop, then (regardless of whether the `_pressed` pseudo prop is set with a nested `_icon` pseudo prop), the `onPress` fires on the **second** click if `Input` had the focus before the first click and `onPress` fires on the **first** click if `Input` did not have focus.

3. NativeBase `Button` and `TouchableOpacity` from `react-native` is behaving the same way as 2.iii.

**Comment by ankit-tailor** [comment]
Hey @zhumingcheng697, Thanks for your investigation. This issue is fixed in `3.4.15`.

**Comment by kpbochenek** [comment]
@ankit-tailor is `3.4.15` already in docs? 
https://docs.nativebase.io/input#h3-password-input
checked `3.4.x` or `next` and they both still have this issue but it might be that docs were not rerendered yet for new version?

**Comment by zhumingcheng697** [comment]
It appears that the issue still persists in the latest build.

The issue seems to be related to how focus was being managed by `<Input>`. Specifically, if the [`onBlur` listener](https://github.com/GeekyAnts/NativeBase/blob/691806cc57c64e90cd3323eaeae39ec605b6b592/src/components/primitives/Input/Input.tsx#L171) was removed from the internal implementation of the `<Input>` component, the click would be registered correctly. If the callback in the listener is fired with a delay, the click would also be registered correctly.

However, neither delaying nor disabling the `onBlur` callback seems to be good solutions to the problem.

What I found out instead was that `onMouseUp` would work perfectly fine on the web.

```tsx
<Input
  {...props}
  rightElement={
    <IconButton
      icon={icon}
      onPress={() => {
        callback();
      }}
      _web={{
        // @ts-ignore
        onMouseUp: (e: MouseEvent) => {
          if (!e.button) {
            callback();
          }
        },
      }}
    />
  }
/>;
```

I added the `onMouseUp` listener only on the web, and I also check for [`e.button`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button) to make sure that the callback is not fired when the user right clicks for context menu. For whatever reason, after adding the `onMouseUp` listener, `onPress` does not seem to be firing on the web, but you can just add another platform check to be extra safe if the callback is not idempotent (i.e. it has “superimposing” effects when being called multiple times).
