### ISSUE TITLE
menu does not work 

### ISSUE THREAD

**Issue by Ahmed-Ibrahim-Anter** [GeekyAnts/NativeBase#4730]
### Description

menu component doesn't work 

### CodeSandbox/Snack link

htt

### Steps to reproduce

started expo template 
put formal code for menu 
no error but didn't work 

### NativeBase Version

3.3.1

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

the menu does not work for me I tried every way but the pressable icon does not do anything I started new expo project and pasted your formal code  but nothing happen
` <Box h="80%" w="90%" alignItems="flex-start">
      <Menu closeOnSelect={false} w="190" onOpen={() => console.log("opened")} onClose={() => console.log("closed")} trigger={triggerProps => {
      return <Pressable {...triggerProps}>
              <HamburgerIcon />
            </Pressable>;
    }}>
        <Menu.OptionGroup defaultValue="Arial" title="free" type="radio">
          <Menu.ItemOption value="Arial">Arial</Menu.ItemOption>
          <Menu.ItemOption value="Nunito Sans">Nunito Sans</Menu.ItemOption>
          <Menu.ItemOption value="Roboto">Roboto</Menu.ItemOption>
        </Menu.OptionGroup>
        <Divider mt="3" w="100%" />
        <Menu.OptionGroup title="paid" type="checkbox">
          <Menu.ItemOption value="SF Pro">SF Pro</Menu.ItemOption>
          <Menu.ItemOption value="Helvetica">Helvetica</Menu.ItemOption>
        </Menu.OptionGroup>
      </Menu>
    </Box>`

**Comment by mazino-dev** [comment]
This wasted my whole in figuring out what was causing the freeze. It turned out to be Menu component, it was working fine earlier.

**Comment by mr-martins** [comment]
Affected: 3.3.6, 3.3.7
I downgraded native base to 3.3.5

**Comment by Lauwed** [comment]
Had the same issue with 3.3.1... I updated to 3.3.7 and the issue is still there.

I downgrade to 3.3.5 and it works. Thanks @mr-martins

**Comment by yuanyujiegit** [comment]
@mr-martins  @Lauwed Thanks
My app got stuck. I checked it for a day and finally found that it was the munu problem

**Comment by chintanbawa** [comment]
thanks @mr-martins and @Lauwed. downgrade to 3.3.5 works for me as well.

**Comment by JAy-Kundariya** [comment]
Add just :- defaultIsOpen={false} in your native-base version:-3.3.7

**Comment by RubenPM-dev** [comment]
Same issue here, any updates on this?

**Comment by surajahmed** [comment]
This issue has been resolved in version `3.3.11`. Thanks for reporting. Going to close this issue. If you face any problems, please feel free to reopen.

**Comment by RubenPM-dev** [comment]
Thanks @surajahmed, I've just updated to 3.3.11, rebuilt my app but the issue is still there on Android (I didn't have an issue with iOS before neither), the whole application gets frozen and I'm getting this error on the console:

`When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server. 
Menu@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app...`

**Comment by Looooong** [comment]
I'm using version `3.3.11`, and still have this freezing problem. Setting `defaultIsOpen={false}` solved it.

**Comment by jigneshkapdiya** [comment]
> defaultIsOpen={false}

this work for in v 3.3.11

**Comment by surajahmed** [comment]
@RubenPM-dev We're working on the SSRProvider warning issue.

**Comment by GollyJer** [comment]
Using native-base v3.4.1

Wasted a bunch of time until finding this thread.
Setting `defaultIsOpen={false}` worked. Thanks @Looooong

**Comment by jqwez** [comment]
I had the same issue. All above suggestions did not work for me. By looking at the Popover section I was able see that the easiest way to negate this error was by adding the following code within the Menu component: 

 isOpen={clearOpen} onClose={() => setClearOpen(!clearOpen)} 

and the following for statefulness: 

const [clearOpen, setClearOpen]= useState(false) 


I am using NativeBase 3.4.7

**Comment by connorpmullins** [comment]
Not a NativeBase issue, but adding for people like me who find their way here:

I passed props to a nested component of the PopoverTrigger:
```
  Box
    Button {...props}
...
```

I was experiencing a situation like the above and the menu wasn't displaying when pushing the trigger. I resolved the issue by making the top-level of the trigger pressable and passing props to that component.
```
  Pressable {...props}
    Box
...
```
using `"native-base": "3.4.28"`

**Comment by VAIMORSS** [comment]
> I'm using version `3.3.11`, and still have this freezing problem. Setting `defaultIsOpen={false}` solved it.

Worked for me.

**Comment by sFarkhod** [comment]
@jqwez same error happened and the solution happened fixed it thank you a lot.
