### ISSUE TITLE
Upgrade native-base overwrites my package.json file.

### ISSUE THREAD

**Issue by stevesweets** [GeekyAnts/NativeBase#476]
Don't really know what else to say.

I have a project running ~0.5.2, i want to upgrade to ~2.0.

I change the package.json version line, run npm install.... package.json is overridden by your package.json file.

If i instead, run `npm install native-base --save`, the same thing happens.

So, what i've done is install it, then revert my package.json file. It'd be handy, to be honest, if that didn't happen, because right now it means i can't run npm update / install without screwing over everything.

**Comment by sankhadeeproy007** [comment]
Yes, just notice that now. That's a very critical bug. Will be fixed first thing tomorrow!
Thanks for reporting.

**Comment by gmccrackin** [comment]
I also had this problem. It just looks like its a problem in the postinsall script where it defines the projectPackage. @stevesweets you can just do `npm install native-base --save --ignore-scripts`. Then add `'eject-native-base': 'node node_modules/native-base/ejectTheme.js',` to the scripts section of your package.json if you want the ability to eject.

**Comment by sherylynn** [comment]
I also had this problem. Waiting for your update

**Comment by sankhadeeproy007** [comment]
Fixed with 2.0.3

**Comment by GroupXTech** [comment]
OMG, I wish I would've gone to the CLOSED items first for this. This is should never had been closed. I just lost my entire package.json config. THANKS.  I've been in the process of removing Native Base from my project for a while. This was the last straw. My advice to anyone new to React-Native DO NOT USE THIS This Repo. The fact that this issue was closed without having the fix in place before adding it to npm is just a small example of the lack of programming standards in this organization.

**Comment by stevesweets** [comment]
@GroupXTech are you saying 2.0.3 doesn't resolve the issue?  2.0.3 was, in fact, released before this issue was closed.

**Comment by GroupXTech** [comment]
Only because you had to use the phrase "IN FACT" is why I'm responding.  I performed and upgrade to native base at 07:15 MST, Feb 8. You closed this issue supposedly 5 hours prior. Your answer is a typical response that I've observed many times to many others when they ask have problems with your hack code. You not doing the react-native community any favors.

**Comment by stevesweets** [comment]
I know you're frustrated, it happened to me yesterday, hence why I reported it. It is not my intention to wind you up further, just to clarify the situation.

I didn't close the issue. I am not a contributor - you shouldn't infer anything I say on the team contributing to this repository.

The issue was only closed 2 hours ago, shortly after 2.0.3 was released.  You can see the timing on the above post by @sankhadeeproy007.

The unfortunate thing is timing - because it meant that you pulled 2.0.2, had the issue, then a couple of minutes later, came here, and saw this issue was closed. 

2.0.3 was released shortly after you pulled 2.0.2, and the issue was closed before you got here.

It sucks, but it doesn't represent a failure on the part of this team, or that this codebase is somehow unreliable.

**Comment by sankhadeeproy007** [comment]
Hi @GroupXTech, it was indeed a bug and we acknowledged it. We also fixed it within 24 hours and only closed the issue after the new release. As for the lost package.json config, I'm sure version control will be able to take care of that. 
Even now it's showing that I closed the issue only 4 hours back. So your claim (3 hours ago) that I closed the issue 5 hours prior to the release is somewhat amusing.

**Comment by sanketsahusoft** [comment]
@GroupXTech First of all, thanks for trying NativeBase 2.0

We regret the inconvenience with `package.json` and it's modification. It was a bug and **we are trying our level best** to keep up the quality of this repo in every way possible.

I understand your frustration and I hope you're using a version control but think about this for a while, from a different perspective -- A group of developers invest 2 months into the development and finally what they get is "**DO NOT USE THIS This Repo**". You don't have any idea what happens to the morale of the developers (or us as human beings).

It's sad to see you go as you mentioned you have been removing NativeBase from your repos lately. But any **constructive criticism** is welcome so that we can make this a better UI library.

Also, I recommend you to read [this article by James Kyle](https://medium.com/@thejameskyle/dear-javascript-7e14ffcae36c#.3s4pqoh97)

Thanks again Jim!
