### ISSUE TITLE
Customize Input component theme no longer working

### ISSUE THREAD

**Issue by pierroo** [GeekyAnts/NativeBase#4951]
### Description

With latest update 3.4.1, customizing template no longer works for some props

### CodeSandbox/Snack link

https://docs.nativebase.io/next/customizing-components

### Steps to reproduce

When using <Input> components, I used to have my extended Theme customized components, most of them now are broken with your latest update.
For example:

```
components: {
    Input: {
      baseStyle: ({ colorMode }) => {
        return {
          bg: colorMode === 'light' ? '#F0F3F7' : BACKGROUND_PRIMARY,
          color: colorMode === 'light' ? '#172B4D' : '#fff',
          borderColor: 'transparent', // => not working
          borderWidth: 0, // => not working
          rounded: 'xl', // => not working
          px: 4,
          py: 3,
          _focus: {
            style: {
              borderColor: '#3BB3EA',
              backgroundColor: colorMode === 'light' ? 'white' : BACKGROUND_PRIMARY,
            }
          },
        }
      },
      defaultProps: {
        fontSize: '16px'
      }
    },
...
```

So now I have to go back to ALL my Input all over the app to customize them inline.
Plus, if I add a rounded props on the input for example, the "focused outline" is completely square without the rounded props!
It used to work just fine, I'm at loss of how impacting this is.

Is it a known issue?

Additional regression:
InputLeftElement + InputRightElement now take their own default greyish background color when main Input is focused; which is not wanted: just like before, I would like those side element to keep the same background as the Input they are attached to.

I guess the documentation isn't updated yet for latest version?
How can I customize Input through BaseStyle? (even placeholder colors, etc)

### NativeBase Version

3.4.1

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hi @pierroo, Thanks for reporting the issue. We'll fix it soon.

**Comment by pierroo** [comment]
Hi @ankit-tailor thank you for looking into it.
I see your latest release 3.4.3 mentioned some changes and fixes for the input, unfortunately it is even more broken than before.
Not only the above still applies, but now there is also a weird issue with padding:
when not focus, padding is respected;
and suddenly when focused, the padding jumped to a different value, then I start typing and now the padding jumps back to normal. Super distracting and unwanted.

Also, now it seems that my customized borderWidth colored on input focused is broken:
![image](https://user-images.githubusercontent.com/17619412/164416197-44e90095-7648-4470-aef3-a2d3a56a6678.png)
Which is a new issue again.

**Comment by Southclaws** [comment]
I'm seeing this too, you can set `defaultProps` in the theme and that works but `baseStyle` does not.

Setting per-component works as a workaround.

**Comment by Viraj-10** [comment]
Hi @Southclaws @pierroo, please use the following code to change `placeholderTextColor`.
we will fix `_light` and `_dark` issues till then please use the following workaround. for now, it's mandatory to pass it inside a `_light` or `_dark`. 

```
 Input: {
        baseStyle: {
          _light: {
            placeholderTextColor: 'red.500',
          },
          _dark :{
            placeholderTextColor: 'white'
          }
        },
      },
```

**Comment by rewrite123** [comment]
Anyone still getting this in July 2022? This bug has been really annoying for me so far having to individually style every input the same way.

**Comment by huynhtastic** [comment]
@Viraj-10 what is mandatory for us to pass in `_light` and `_dark`? Do we need to do this for all custom theming or just placeholderTextColor?

**Comment by Viraj-10** [comment]
Hi @huynhtastic, for now, it's for all the colour-specific props. We are working on this issue. It will be fixed in an upcoming release.

**Comment by ankit-tailor** [comment]
Hi everyone, Thanks for your patience. This issue is fixed in `3.4.15`.

**Comment by vajiralasantha** [comment]
I was gonna use this for one of my project and turned out non of  these methods worked for me. After spending hours, for some reasons only the following method worked for me.

```
components: {
    Heading: {
      baseStyle: ({colorMode}) => {
        return {
          _dark: {color: 'icon.add'},
          _light: {color: 'icon.trendUp'},
        };
      },
    },
  },
```

Im using 

```
    "native-base": "3.4.17",
    "react": "18.2.0",
    "react-native": "0.70.1",
```

**Comment by spsaucier** [comment]
I'm still unable to change `outline` variant styles in version `3.4.17`.

```
    variants: {
      outline: {
        baseStyle: {
          _focus: {
            borderColor: 'primary.300',
            bg: 'transparent',
          },
        },
      },
    },
```
<img width="278" alt="Screen Shot 2022-10-05 at 14 05 26" src="https://user-images.githubusercontent.com/596143/194130611-10010744-d979-4f76-aee1-f5c6034d1968.png">

**Comment by anthonyringoet** [comment]
Still works on 3.2.2, did not work as expected in the most recent 3.4.x releases for me.

**Comment by czaku** [comment]
Also for me, I cannot style the input properly, what is weird styling works in light mode but not in dark mode.... native-base 3.4.25 with iOS 16.2 simulator (latest react native 0.71.2).

**Comment by czaku** [comment]
@ankit-tailor can we reopen this issue as clearly from comments still exists?
