### ISSUE TITLE
Modal avoidKeyboard not work

### ISSUE THREAD

**Issue by jonahcui** [GeekyAnts/NativeBase#5041]
### Description

when I open the example that uses a input inside a modal and set avoidKeyboard. The input component will be  overlay by keyboard. 

### CodeSandbox/Snack link

https://docs.nativebase.io/modal#h3-modal-with-avoidkeyboard

### Steps to reproduce

1. Go to '[Documention](https://docs.nativebase.io/modal#h3-modal-with-avoidkeyboard)' 
2. Click on 'run ios' 

### NativeBase Version

3.4

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
This issue has been fixed in NativeBase `v3.4.7`.

**Comment by adamryvola** [comment]
The behaviour is still the same. I tested that on Android and iOS too.

**Comment by amawaziny** [comment]
It's not working on version 3.4.25, I tested it on android expo go

**Comment by carlos19960601** [comment]
same issue in NativeBase 3.4.25

**Comment by holmesjr** [comment]
This issue still exists with Android and native-base 3.4.25

**Comment by leciric** [comment]
I made this as a work around while it is not available.


Added a new hook to the project, that returns if the keyboard is open or not.

```tsx
import { useEffect, useState } from 'react';
import { Keyboard } from 'react-native';

export function useKeyboard() {
  const [isKeyboardVisible, setKeyboardVisible] = useState(false);

  useEffect(() => {
    const keyboardDidShowListener = Keyboard.addListener(
      'keyboardDidShow',
      () => {
        setKeyboardVisible(true);
      },
    );

    const keyboardDidHideListener = Keyboard.addListener(
      'keyboardDidHide',
      () => {
        setKeyboardVisible(false);
      },
    );

    return () => {
      keyboardDidHideListener.remove();
      keyboardDidShowListener.remove();
    };
  }, []);

  return isKeyboardVisible;
}

```

Then using this hook I added a padding bottom of 50% to the modal style

```tsx
const isKeyboardOpen = useKeyboard();
```

```tsx
<Modal
  isOpen={isModalOpen}
  onClose={() => handleCloseModal()}
  pb={isKeyboardOpen ? '50%' : '0'}
>
```

Seems to work just fine, tested using expo go.

**Comment by JosephLu2022** [comment]
+1 3.25 doesn't work still

**Comment by jnariai** [comment]
A workaround is to set RNModal to false
```
      <Modal
        _overlay={{
          useRNModal: false,
          useRNModalOnAndroid: false,
        }}
        overlayVisible={false}
      >
   ```
