### ISSUE TITLE
CheckBox.Group bugs

### ISSUE THREAD

**Issue by btrewern** [GeekyAnts/NativeBase#5073]
### Description

Check boxes change randomly when in a CheckBox.Group

### CodeSandbox/Snack link

See document examples

### Steps to reproduce

Loading either CheckBox.Group examples:

https://docs.nativebase.io/checkbox#h3-controlled or https://docs.nativebase.io/checkbox#h3-uncontrolled

the check boxes don't work as expected.  The first select click works but after that check boxes seem to change at random.

Also when running locally these examples raise a Console Warning as follows:

"We can not support a function callback. See Github Issues for details https://github.com/adobe/react-spectrum/issues/2320"

### NativeBase Version

3.4.6

### Platform

- [x] Android
- [ ] CRA
- [x] Expo
- [x] iOS
- [ ] Next

**Comment by Krithikj20** [comment]
Hi @btrewern, Thank you for reporting this issue. We will look into it.

**Comment by chornos13** [comment]
Yeah, I experienced the same. this is major bug because the Component not updated when trigger by HMR

**Comment by Viraj-10** [comment]
Hi @chornos13, this issue is fixed. We are upgrading the native-base version in docs. This is a docs issue.

**Comment by ttessman** [comment]
Still see the warning in 3.4.13

<img width="405" alt="image" src="https://user-images.githubusercontent.com/8061029/193949969-6b8d0250-a8d2-4d31-93b2-9adc9957a51b.png">

**Comment by guidoabelleira** [comment]
I have the same problem in "native-base": "^3.4.6".

> Todavía veo la advertencia en 3.4.13
> 
> <img alt="imagen" width="405" src="https://user-images.githubusercontent.com/8061029/193949969-6b8d0250-a8d2-4d31-93b2-9adc9957a51b.png">



> Todavía veo la advertencia en 3.4.13
> 
> <img alt="imagen" width="405" src="https://user-images.githubusercontent.com/8061029/193949969-6b8d0250-a8d2-4d31-93b2-9adc9957a51b.png">


did you find a solution?

Logro resolver?

**Comment by mlab817** [comment]
well, i still have the problem.

**Comment by sahilvasuja** [comment]
For now, you can try this one [checkbox group] (https://snack.expo.dev/@sahil_vasuja/checkbox_group)

**Comment by hananiradzi** [comment]
Still have same issue with latest version. 3.4.25

**Comment by kokosky93** [comment]
guys how did you solve the problem?

I have no idea how to solve it nothing is working no matter whether is it a simple checkbox or a group of checkboxes.

It is randomly checking checkboxes. I don't know what has changed because there was no update this package last 6 months

**Comment by ntrphongse** [comment]
For some who are suffering this problem, I found out the the issue was mentioned and solved here at https://github.com/GeekyAnts/NativeBase/issues/5098#issuecomment-1579910908

They fixed it in https://github.com/GeekyAnts/NativeBase/pull/5686 but I don't know why it returned to the buggy version (maybe in https://github.com/GeekyAnts/NativeBase/pull/5702)

Native-base team please have a look!

**Comment by jy1989** [comment]
so long time, same bug we facing

**Comment by meypod** [comment]
I was able to workaround the issue by wrapping the checkbox with a Pressable, added `pointerEvents='none'` around the checkbox, stopped using the checkbox or checkbox group's onChange. and toggled the value of checkbox by the Pressable's onPress.
I could not use the `isChecked` property, so I continued to use checkbox group and the value prop.

I hope this helps somebody out there looking for a workaround.

**Comment by agnieszka-wojcik-dev** [comment]
> guys how did you solve the problem?
> 
> I have no idea how to solve it nothing is working no matter whether is it a simple checkbox or a group of checkboxes.
> 
> It is randomly checking checkboxes. I don't know what has changed because there was no update this package last 6 months

I solved this problem by changing value={someValue} to defaultValue={someValue}
