### ISSUE TITLE
Select: unsetting the value has no effect

### ISSUE THREAD

**Issue by astriskit** [GeekyAnts/NativeBase#5077]
### Description

When trying to clear the value of a controlled Select element using `undefined`, `null` or `""`/empty-string, the element doesn't change the selected-value in the ui. This action should unset the selected-value in ui.

### CodeSandbox/Snack link

https://snack.expo.dev/O8jLa_m9k

### NativeBase Version

3.4

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hi @astriskit, This issue is fixed in version `3.4.7`. Let me know if it works for you.

**Comment by Siliconvelly** [comment]
Well i am still facing this issue i am using native-base@3.4.20. so please fix this issue as soon as possible.

**Comment by recepaltas** [comment]
same
