### ISSUE TITLE
Custom variants not working on Heading component

### ISSUE THREAD

**Issue by smeads-sweater** [GeekyAnts/NativeBase#5343]
### Description

Custom variants extending the theme for the Heading component aren't working

### CodeSandbox/Snack link

https://snack.expo.dev/@smeads/nativebase-template

### Steps to reproduce

1. Try using the `variant` prop on the `Heading` component.
2. Using the `size` prop works as expected.

### NativeBase Version

3.4.15

### Platform

- [X] Android
- [X] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Other Platform

React Native

### Additional Information

I'm experiencing an issue with extending the theme. Specifically, I've extended both the `Heading` and `Text` components with variants in the `components` config. When I use the `variant` prop for `Heading` the `variant` doesn't work, I only see default variants. However, It does work for `Text`. I'm also not getting type inference (TS) even though I have properly extended the ICustomTheme with my CustomThemeType. Again, type inference is working on Text.

Using the `size` prop does work, just to clarify.

I've tried to get the expo snack as closely to how I have it implemented. The snack experiences the same issue, so it is reproducible.

I apologize if I'm missing something but I've read through docs, looked over several other code examples and I'm not seeing where I'm messing things up. Any help with this issue would be appreciated. And, thank you for a great component library.

NativeBase Version - 3.4.15
React Native Version - 0.68.3

**Comment by smeads-sweater** [comment]
I've been working with this a bit more and the variant does appear to work, but it doesn't respect the `fontSize`. If I add a `color` property to one of the `Heading` variants the color will reflect as expected, but the size will not.

```
    h3: {
      fontSize: '24px',
      color: 'error.500',
    },
```

**Comment by ankit-tailor** [comment]
Hey @smeads-sweater, [Here](https://stackoverflow.com/questions/73044944/how-to-use-the-nativebase-theming-functionality-to-make-different-header-variant/73047972#73047972) I've explained how size is getting resolved in heading component. You can refer to it. closing this issue for now, feel free to re-open it if you have any doubts.

**Comment by smeads-sweater** [comment]
@ankit-tailor thank youi for the link and appreciate the explanation. Will NativeBase still not pick up the type inference for Heading variants?

**Comment by ankit-tailor** [comment]
Hey, typing is fixed in `3.4.15`. Which version are you using?

**Comment by smeads-sweater** [comment]
@ankit-tailor using `3.4.15`. I've created a `theme.d.ts` file per the NativeBase docs.

```
import customTheme from 'theme';

type CustomThemeType = typeof customTheme;

declare module 'native-base' {
  interface ICustomTheme extends CustomThemeType {}
}
```

**Comment by localjo** [comment]
@ankit-tailor I'm having the same problem, and the solution you linked on Stack Overflow is missing an important piece. The `size` needs to be defined per-variant, not at the defaultProps level for all Heading components. Here's a Snack example of the problem: https://snack.expo.dev/@localjo/custom-heading-variant-example

Basically, with `extendTheme` I should be able to set `Heading.variants[name].size` and it should be applied, but it is not. Other props like `textTransform` and `color` work fine.

**Comment by epshtielsl** [comment]
Also seeing this issue.  Defining a size for a `Heading` variant is being ignored.

**Comment by kfekairii** [comment]
I resolved it this way:
```
<Text color={cod?.status === 'FAILED' ? 'text.500' : 'text.900'}>
  <Text fontWeight={'semibold'}>
    SEMIBOLD TEXT
  </Text>
</Text>
```
