### ISSUE TITLE
[BUG] CardItem flex box issue in iOS on Plus version screen

### ISSUE THREAD

**Issue by Anima-t3d** [GeekyAnts/NativeBase#612]
There seems to be an issue revolving around **iPhone Plus screens** and **usage of multiple `CardItem` components**. In certain edge cases the `CardItem` can **affect the display of the next** `CardItem`. Possibly when width/height layout properties are incorrectly rounded, resulting in 1 pixel gap for flex-box items to stack horizontally.

## react-native, react and native-base version
"native-base": "^2.0.12",
"react": "~15.4.1",
"react-native": "0.42.0",
## Expected behaviour
When using `CardItem` having the content contained nicely inside the container element.
## Actual behaviour
On iPhone Plus versions the content can break outside of the container element. (Floats on the right side, as if there is a 1 pixel gap for the content to position itself)
### Possible causes

- `style` with `margin`(top/bottom)/`padding`(top/bottom)/`height`/`fontSize` on for example H3
- content of H3 too short
### Possible quick fixes

- `style` with `margin`(top/bottom)/`padding`(top/bottom)/`height`/`fontSize` on `CardItem`/`Card` or content in `CardItem`
- move the affected `CardItem` above the `CardItem` that causes the issue
- add a dummy `CardItem` with `style` with `margin`(top/bottom)/`padding`(top/bottom)/`height`
### Possible affected elements

- Button, CheckBox, Radio, Grid
#### Working
```JavaScript
<Card>
              <CardItem>
                <Body>
                  <H3>
                    Expected
                  </H3>
                </Body>
                <Right>
                  <Text note>OPTIONAL</Text>
                </Right>
              </CardItem>
              <CardItem>
                <Body>
                  <Button iconLeft bordered onPress={() => {console.log('clicked add assets')}}>
                    <Icon name="md-add" />
                    <Text>Add Things</Text>
                  </Button>
                </Body>
              </CardItem>
            </Card>
```
#### Not working
```
<Card>
              <CardItem>
                <Body>
                  <H3 style={{marginBottom: 20}}>
                    Broken
                  </H3>
                </Body>
                <Right>
                  <Text note>OPTIONAL</Text>
                </Right>
              </CardItem>
              <CardItem>
                <Body>
                  <Button iconLeft bordered onPress={() => {console.log('clicked add assets')}}>
                    <Icon name="md-add" />
                    <Text>Add Things</Text>
                  </Button>
                </Body>
              </CardItem>
            </Card>
```
### Working on Android
![android](https://cloud.githubusercontent.com/assets/830386/23694959/c3c095a0-0417-11e7-8b50-33517140e411.png)
### Broken on Plus version
![ios_plus](https://cloud.githubusercontent.com/assets/830386/23694961/c592bb60-0417-11e7-8830-00fbd66791ae.png)
> Note the red arrow indicating where the content was pushed outside of the view.

## Is the bug present in both ios and android or in any one of them?
IOS plus version only
## Any other additional info which would help us debug the issue quicker.
The issue only occurs on iPhone Plus (both 6 and 7 versions)

**Comment by shivrajkumar** [comment]
You can just fix this by applying transparent backgroundColor for the Text

**Comment by cyclops24** [comment]
@shivrajkumar it's not fix for me in related issue with `transparent backgroundColor`. I think this bug is about card layout system. See #669

**Comment by Anima-t3d** [comment]
@cyclops24 Indeed I think @shivrajkumar misunderstood the issue. The issue is not that the header (with the text **Broken**) has a white background. The issue is that the content which was supposed to be below the header is suddenly "floating" on the right. Putting a transparent background would show the border, but doesn't solve the main issue, which is the content being in the wrong position.

**Comment by shivrajkumar** [comment]
@Anima-t3d @Anima-t3d @cyclops24 Just to be clear. By "content", do you mean the note "OPTIONAL" or the "ADD THINGS" Button. And is the issue with the Button or the note?

**Comment by Anima-t3d** [comment]
@shivrajkumar I mean the "ADD THINGS" Button. In the **expected** version you can see what I would expect to get. When I add `marginBottom` on the `H3` element, it breaks the layout on Plus devices. The arrow indicates where the button shifted off-screen.

**Comment by didil** [comment]
getting the same issue on iphone 7 plus simulator

**Comment by cyclops24** [comment]
Please fix this. It's a biiiiiiiiiiiiiiiiiiiiiiiiig bad issue for me and make card very buggy.

**Comment by seanmadi** [comment]
Having the same issue on iPad Air 2 (and simulator). Everything looks fine on load, but if I rotate and then rotate back, the second CardItem (everything that isn't the header) floats to the right of the header. For some reason it works fine on the first iPad Air. May have something to do with height of the card being shorter when rotated, then it for some reason remains 

```
<Card>
  <CardItem header bordered>
    <Text>Last Encounter Information</Text>
  </CardItem>
  <CardItem>
    <View>
      <Text style={styles.textWrapper}>
        <Text style={styles.label}>Date:</Text> 12/12/2016
      </Text>
      <Text style={styles.textWrapper}>
        <Text style={styles.label}>Goal:</Text> Accomplish a really important thing
      </Text>
      <Text>Some really long text some really long text some really long text some really long text some really long text</Text>
      <Text>Some really long text some really long text some really long text some really long text some really long text</Text>
      <Text>Some really long text some really long text some really long text some really long text some really long text</Text>
    </View>
  </CardItem>
</Card>
```

<img width="786" alt="screenshot at may 15 11-28-24" src="https://cloud.githubusercontent.com/assets/576752/26065365/ae2ffef4-3961-11e7-9418-a63d7c69f5f1.png">

<img width="801" alt="screenshot at may 15 11-28-41" src="https://cloud.githubusercontent.com/assets/576752/26065369/b224ed62-3961-11e7-89d7-675e9a4478f6.png">

**Comment by seanmadi** [comment]
For my issue at least, it looks like it is due to Card having `flexWrap` of `'wrap'`. Created my own components with the same styles minus flexWrap and it now works fine.

**Comment by SupriyaKalghatgi** [comment]
#668

**Comment by SupriyaKalghatgi** [comment]
#669

**Comment by SupriyaKalghatgi** [comment]
iPhone 6
![simulator screen shot jun 1 2017 3 21 35 pm](https://cloud.githubusercontent.com/assets/13464885/26675300/0c61c87c-46e1-11e7-8da5-8e43dd8240da.png)


iPhone 6 Plus
![simulator screen shot jun 1 2017 3 24 01 pm](https://cloud.githubusercontent.com/assets/13464885/26675323/1ddea7a0-46e1-11e7-95a3-26cc93f2217b.png)


iPhone 7 Plus
![simulator screen shot jun 1 2017 3 42 28 pm](https://cloud.githubusercontent.com/assets/13464885/26675336/298d164a-46e1-11e7-86eb-e49c170c1a76.png)


Checked for all these simulators, and the Card functions constantly
May be you can check with the latest of NativeBase [2.1.4](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.1.4)

**Comment by SupriyaKalghatgi** [comment]
@cyclops24 The above screenshots show that cards are working fine on iPhone 6, 6+, 7+

**Comment by SupriyaKalghatgi** [comment]
@sankhadeeproy007

**Comment by sushant6309** [comment]
@SupriyaKalghatgi I think issue is not fixed.
I am using the version: 2.3.1
![image](https://user-images.githubusercontent.com/11680830/31328813-9655ddec-acf4-11e7-9aba-54d83ea4b2d5.png)

As I give padding top on current amount text view in Iphone 6+ and 7+ is disturbed but in iphone 5s, 6, 7 it working fine.

**Comment by AshokICreate** [comment]
i am facing similar issue. why is this issue closed without resolving?

The Layout which i designed looks good in iPhone 5, iPhone 6, iPhone 7 but it messed up with iPhone Plus devices when i am using card item.

**Comment by SupriyaKalghatgi** [comment]
@sushant6309 @AshokICreate The issue was fixed and tested with NB 2.1.4, please check above comments for same

Though I have reopened this issue, we will look into this

**Comment by AshokICreate** [comment]
FYI I am using "native-base": "^2.3.2", version @SupriyaKalghatgi 

Thanks for reopening the issue and your quick reply. i fixed the issue which i had by replacing entire native base components with react-native components.

**Comment by sushant6309** [comment]
I had also fixed my issue by replacing the nativebase components with react native components. But the problem still remains in nativebase components.

**Comment by SupriyaKalghatgi** [comment]
@AshokICreate @sushant6309 we are looking into it
we hope you to get back using NativeBase in your projects

**Comment by akhil-geekyants** [comment]
Fixed in the latest version (2.3.5)

Screenshots

iPhone 6 plus 

![simulator screen shot - iphone 6 plus - 2017-12-18 at 16 00 10](https://user-images.githubusercontent.com/27768184/34101840-1405d0ea-e40d-11e7-8845-d3ec45a20f67.png)


iPhone 7 plus

![simulator screen shot - iphone 7 plus - 2017-12-18 at 15 58 19](https://user-images.githubusercontent.com/27768184/34101849-1ac8bbea-e40d-11e7-90cf-fb2980505cee.png)

**Comment by kimchirichie** [comment]
I have experienced the exact same issue on native base v2.8.1. It only appeared in iphone plus series. Fixed by introducing `<Card style={{ flexWrap: "nowrap" }} />` You may also apply this to all nativebase Cards by changing one line in `theme/components/Card.js`
