### ISSUE TITLE
Input value and floating label

### ISSUE THREAD

**Issue by luksfk** [GeekyAnts/NativeBase#627]
Hi,

I'm using floating label on a simple input. When I pass value to this component, the label subscribe the value. If I enter the input and press something, label works nice. I tried autoFocus but when I just exit, label subscribe again.

![image](https://cloud.githubusercontent.com/assets/18454608/23803451/5bbb30f8-0595-11e7-9827-49cc65abcef5.png)

![image](https://cloud.githubusercontent.com/assets/18454608/23803344/f9053e86-0594-11e7-8a75-9076159e398c.png)

"native-base": "^2.0.12",
"react-native": "0.42.0",
"react": "15.4.2"

**Comment by iiitmahesh** [comment]
icon color also not working for Form item floating labels #629

**Comment by sankhadeeproy007** [comment]
cc @shivrajkumar

**Comment by BaptWaels** [comment]
I've got the same problem

**Comment by fkrauthan** [comment]
Same problem for me. I connected form-redux and every time I leave the input the floating label goes back as it assumes the text field is empty.

**Comment by fkrauthan** [comment]
@luksfk are you using redux-form by any chance and run into this issue?

**Comment by Colmea** [comment]
+1 . Any news on this ?

**Comment by luksfk** [comment]
@fkrauthan  yes, i'm using redux.

**Comment by fkrauthan** [comment]
@luksfk My issue was that I was doing something like this:

```
<Field name="lastName" component={() => this.renderMyInput()} type="text"/>
```

This recreated the input field every time I was pressing a key. After changing this to the recommended way of

```
<Field name="lastName" component={this.renderMyInput} type="text"/>
```

It was working fine. I think native base has a problem with there javascript code if the underlying input field gets recreated instead of just updated.

**Comment by BrunoQuaresma** [comment]
is in production?

**Comment by yugalbagul** [comment]
when will this be available in production ?

**Comment by sankhadeeproy007** [comment]
By the end of this week.

**Comment by sankhadeeproy007** [comment]
Fixed with 2.1.5

**Comment by shivrajkumar** [comment]
Check the latest version 2.2

**Comment by oximer** [comment]
@sankhadeeproy007 When 2.1.5 will be release?
The latest release to me is 2.1.4

**Comment by shivrajkumar** [comment]
@oximer The latest of NativeBase is 2.2.1
Check the release tags

**Comment by slorber** [comment]
@shivrajkumar for me this issue is not resolved in 2.2.1, and is the same as https://github.com/GeekyAnts/NativeBase/issues/1073

**Comment by tondapup** [comment]
Its working fine in iOS Simulator, but overlapping in iPhone.

**Comment by qwerty94155** [comment]
working fine on iOS simulator but overlapping in iPhone

**Comment by blkmutt** [comment]
Is there a chance the release build is not right here? This appears to work in Debug, but not Release, even in the simulator.

**Comment by slorber** [comment]
@akhil-geekyants for what it's worth, in glamorous-native we had a problem affecting only release builds. I have no idea if this is related but as people report it's only affecting release it might be worth checking.


On new RN versions, only in release mode, the exported View is not a function but is a string "RCTView" while it was previously a function. If lib code expects a function it might break.

See here for more details: https://github.com/robinpowered/glamorous-native/pull/85

**Comment by ryanlanciaux** [comment]
Not big on the "me too" comments but I'm bumping into this in release builds and not totally sure what to do to mitigate.

**Comment by svlada** [comment]
I have same problem as well. Please find use cases below

**Working fine - not overlapping**
```
<Content>
        <Item stackedLabel>
            <Label>
              {this.state.label}
            </Label>
          <Input
            keyboardType={this.props.keyboardType ? this.props.keyboardType : 'default' }
            onChangeText={(value) => this.onChange(value) }
            value={this.state.value}
          />
</Content>
```

**Not Working fine - overlapping**
```
<View>
        <Item stackedLabel>
            <Label>
              {this.state.label}
            </Label>
          <Input
            keyboardType={this.props.keyboardType ? this.props.keyboardType : 'default' }
            onChangeText={(value) => this.onChange(value) }
            value={this.state.value}
          />
</View>
```

**Comment by baskan** [comment]
this is a huge problem imho. I didn't realised this until we "shipped" product with release configuration and animations are not working properly in the release mode, 
shutters and overlapping due to its not properly rendering last frames.

**Comment by rouge3351** [comment]
i'm same problem! in native-base 2.3.9!

**Comment by inanbayram** [comment]
I have also the same problem. This happens only in the release mode. version 2.3.9

**Comment by spencercharest** [comment]
I'm also seeing this issue on 2.3.9 and 2.3.10

**Comment by spcotter** [comment]
In release, the displayName of the Input is set to "Styled(t)" instead of the expected "Styled(Input)". This prevents the inputProps from being set in [componentWillReceiveProps](https://github.com/GeekyAnts/NativeBase/blob/6551e42f7782a0591dc8afc8f82afb2a46b17852/src/basic/Item.js#L37) so the value isn't recognized as being set.

```javascript
componentWillReceiveProps(nextProps) {
    const childrenArray = React.Children.toArray(nextProps.children);
    let inputProps = {};
    _.remove(childrenArray, item => {
      if (item.type.displayName === "Styled(Input)") {
        inputProps = item.props;
        this.inputProps = item.props;
        return item;
      }
    });
```
Example Snack:
https://snack.expo.io/SJqB3fu5M

A hackish fix is to set the displayName directly after importing with`Input.displayName = 'Styled(Input)';`  as here:
https://snack.expo.io/@spcotter/native-base-floating-label-issue-627-patch

The label displayName is also "Styled(t)".

**Comment by baskan** [comment]
nice find @spcotter !

**Comment by joshm101** [comment]
@spcotter this worked for us! Thank you!

**Comment by timhuff** [comment]
I've tried @spcotter's fix and it's not working for me. `native-base@2.3.1`

**Comment by spcotter** [comment]
@timhuff were you able to output `Input.displayName` in release to see if it's correct? I couldn't get snack to install `native-base@2.3.1`.

**Comment by timhuff** [comment]
@spcotter I'm pretty sure I verified that - I spent a decent amount of time trying to get it to work. I'll double check here when I get second. For now, I decided to just stop using floating labels and go with the default behavior until this feature's a bit less buggy. It's not as nice but it's better than giving my users the impression on the get-go (login) that the app is buggy.

**Comment by amalpba** [comment]
I've got the same problem

**Comment by itcurves** [comment]
I am having the same issue. how soon we can get an update on it? it only happen when input already filled in.

**Comment by victorwads** [comment]
I have the same issue, when the input layout starts with data, the floating label just "get up" after the first focus/blur
Ps.: This not happens on Emulator, just real devices

![2](https://user-images.githubusercontent.com/20746587/38787644-bdf6571e-4105-11e8-82ea-a526b90baa84.jpg)

**Comment by itcurves** [comment]
are we going to have an update on this soon?

**Comment by Rud156** [comment]
This problem still occurs in `native-base@2.4.5`

**Comment by jpolo** [comment]
I found a workaround. If possible, use controlled input (i.e. set the value)

**Comment by RCulpepp** [comment]
Attempted to use the fix by @spcotter, but still having the same issue.  @jpolo - can you elaborate on what you mean by a controlled input?

**Comment by jpolo** [comment]
It's from react doc : https://reactjs.org/docs/forms.html#controlled-components

**Comment by brayanL** [comment]
the problem still persist on Android and IOS, when I read the value assigned to onChangedText I do not get all the input

**Comment by anthlasserre** [comment]
It's just you have to use like this (with value):
`<Input
    value={this.state.name}
    onChangeText={ (text) => this.setState({ name: text }) }
 />`
Because the input don't know the value so by default it's null.

**Comment by pinchez254** [comment]
ensure have  added value field geuss native base assumes you have to add it by default,,
like this  <Label>Email</Label>
              <Input
              value={this.state.email}
                autoCapitalize="none"
                onChangeText={text => this.setState({ email: text })}
              />
works like charm on both android and ios.

**Comment by suvenduchhatoi** [comment]
Anyone still having the issue :Please upgrade your "react-native" and "native-base" versions...and check...An example code for you below...should work perfectly fine both in Ios and Android... Label floats up perfectly-

```

import React, { Component } from "react";
import { StyleSheet, View, TextInput } from "react-native";
import {
  Container,
  Content,
  Form,
  Item,
  Input,
  Label,
  Text,
  Left,
  Right,
  Body,
  Card,
  CardItem,
  Button,
  Separator,
  Icon,
} from "native-base";

const styles = StyleSheet.create({
  label: {
    fontSize: 15,
    color: "#fff",
    lineHeight: 20,
  },
});
export default class Register extends Component {
  constructor(props) {
    super(props);
    this.state = {
      data: { name: "", email: "", password: "" },
    };
  }
  updateValue(text, field) {
    const { data } = this.state;
    data[field] = text;
    this.setState({
      data,
    });
  }

  submit() {
    //Action
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <Container
          style={{
            margin: 10,
            marginTop: 40,
          }}
        >
          <Content>
            <Card
              style={{
                backgroundColor: "green",
                margin: 20,
              }}
            >
              <Left />
              <Body>
                <CardItem
                  header
                  bordered
                  style={{
                    margin: 10,
                  }}
                >
                  <Text>
                    <Icon active name="home" />
                    REGISTRATION FORM
                  </Text>
                </CardItem>
              </Body>
              <Right />
              <Form
                style={{
                  margin: 20,
                }}
              >
                <Item floatingLabel>
                  <Label style={styles.label}>Username</Label>
                  <Input
                    style={styles.label}
                    onChangeText={text => this.updateValue(text, "name")}
                  />
                </Item>
                <Item floatingLabel>
                  <Label style={styles.label}>Email</Label>
                  <Input
                    autoCapitalize={"none"}
                    style={styles.label}
                    onChangeText={text => this.updateValue(text, "email")}
                  />
                </Item>
                <Item floatingLabel>
                  <Label style={styles.label}>Password</Label>
                  <Input
                    autoCapitalize={"none"}
                    style={styles.label}
                    onChangeText={text => this.updateValue(text, "password")}
                  />
                </Item>
              </Form>
            </Card>
            <Button full primary onPress={() => this.submit()}>
              <Text> REGISTER </Text>
            </Button>
          </Content>
        </Container>
      </View>
    );
  }
}
```

**Comment by suvenduchhatoi** [comment]
Closing the issue due to no response for a while...Hope your issue has been resolved.You can reopen the issue if you still feel the issue is exclusive to "native-base"...

**Comment by arfa123** [comment]
this issue is still happening.
"react-native": "^0.57.4", "native-base": "^2.8.1",
![screenshot_2019-01-21-14-36-06](https://user-images.githubusercontent.com/16974364/51465689-3d246b00-1d8a-11e9-90f4-d3650bbb4a73.png)

**Comment by nitishdhar** [comment]
Still happening in `2.12.1`

**Comment by SupriyaKalghatgi** [comment]
Working
![image](https://user-images.githubusercontent.com/13464885/54413916-75f31780-471d-11e9-92c1-f5ffd367ffbb.png)
