### ISSUE TITLE
Refresh control not working with nativebase components

### ISSUE THREAD

**Issue by sathish932** [GeekyAnts/NativeBase#69]
![capture](https://cloud.githubusercontent.com/assets/19871729/16956415/027d702a-4df6-11e6-9334-39bf685bd147.PNG)
![capture1](https://cloud.githubusercontent.com/assets/19871729/16956432/088262fa-4df6-11e6-9a4f-d9742711efca.PNG)

**Comment by Chion82** [comment]
Same problem. And adding `refreshControl` prop directly to `<content>` even causes `maximum call stack size exceeded` exception

**Comment by sankhadeeproy007** [comment]
Fixed in 0.5.5

**Comment by mariusandra** [comment]
Hey, unfortunately it's not fixed. Waiting for a "maximum call stack exceeded" error before using shallow merge is a very very slow solution. It can take seconds for the stack to fill itself and the exception is raised.

Is there any reason props can't be shallow merged by default? It seems like a normal and sensible approach to me, as you should never mutate the props anyway, so why clone that deep?

**Comment by sankhadeeproy007** [comment]
Hi, @mariusandra could you send a PR with your proposed solution?

**Comment by Chion82** [comment]
@mariusandra Agree. Actually I'm also confused why use deep merge, and afraid of breaking anything, I just added that try-catch clause in #109 . Yeah, outgoing props shouldn't and cannot be mutated in principal, so using shallow merge by default should be just fine. Why not give it a try :)

**Comment by mariusandra** [comment]
The PR is here: https://github.com/GeekyAnts/NativeBase/pull/152 , thanks!

**Comment by Chion82** [comment]
By the way, it seems interesting why the deep merge hangs. Is there a reference loop in the generated React component (as a plain JavaScript object) that causes the infinite clone?

**Comment by sankhadeeproy007** [comment]
@mariusandra The reason for doing a deep merge was to preserve any other prop which the user might be sending. As we don't want to be losing out on any user sent prop. We can however put in a condition where we check the prop type, if the type is a function, we'll do the shallow merge otherwise we'll stick to merge.

**Comment by mariusandra** [comment]
@sankhadeeproy007 Sorry, I'm not sure I follow. How will the props not be preserved with a shallow merge? The way I have understood is that it's always preferred to do a shallow merge, as the props will never be mutated downstream and this is way way faster.

All the code I find these days just uses `Object.assign({}, oldState, newState)` to shallowly clone and merge props.

**Comment by Chion82** [comment]
@mariusandra With shallow merge, when user sends props containing a top-level key that already exists in the default props, the value of that key will be lost. Say, user passes `{myProp : { myKey : 1  }}` and we have a `{myProp : { defaultKey : 1 }}` by default,  we prefer `{myProp : { myKey : 1 , defaultKey : 1}}` as our result, instead of either one of them.

**Comment by mariusandra** [comment]
Ah, I get it now, thanks. What to do then?

**Comment by Chion82** [comment]
As @sankhadeeproy007 says, putting in a condition to check every prop type before merging should solve the problem. Maybe the checking logic should be deep too.

**Comment by sgentile** [comment]
when I put it inside content, it fires and shows the spinner - however I get this error 

```
Exception thrown while executing UI block: -[RCTView contentOffset]: unrecognized selector sent to instance 0x7ff19850cec0
```

**Comment by Thunderbird7** [comment]
Hi, i found the same issue. How to fix it ?

**Comment by adulhani-systango** [comment]
+1

**Comment by sankhadeeproy007** [comment]
The same way you would add it inside `ScrollView`.

**Comment by milkers** [comment]
I changed it to `ScrollView` but still get the same error. I know it is not directly related to NativeBase but it is still related somehow. Do you have any working example of `RefreshControl` inside `Content`? Or anyone knows why this exception fires?

**Comment by Xosmond** [comment]
Well I arrive here with the same problem. Did Anybody solve it?

**Comment by ceefour** [comment]
Hi @Xosmond, check out #1192 for a related bug and see #269 (especially @axsann's) for possible alternatives for you, although none are satisfactory at the moment when TabNavigator is involved.

**Comment by saurabhabh** [comment]
Hello is there any working example for the same ? where in we can apply the RefreshControl to the 'Content' or 'List' ? I am still facing issues with this. I am using native base '2.6.1' and react native 0.55.4
`  <Content refreshControl={this._refreshControl()}> 
<List></List> ...
</Content>
`
below is attaching an image for the snippet code.
![image](https://user-images.githubusercontent.com/8706481/44894442-6118de80-ad0d-11e8-82b9-db7841e67b02.png)


The Code for Refresh Control is 
![image](https://user-images.githubusercontent.com/8706481/44894373-0d0dfa00-ad0d-11e8-9e97-c5894c31fcf6.png)

The consoleLog code is as follows
![image](https://user-images.githubusercontent.com/8706481/44894389-244ce780-ad0d-11e8-9404-9c206d1d8335.png)

With this code in place I am getting the error - 

> Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

Can some one point out what is wrong with my code ? or what I need to do to fix it ?

**Comment by SupriyaKalghatgi** [comment]
@saurabhabh There are many similar issues provided with solution, you ca n check them across NativeBase github

**Comment by saurabhabh** [comment]
@SupriyaKalghatgi  Hi I did check them. But None of them seem to work. Hence I am asking if there is a working example with the refresh control added to the 'Content'. As few have suggested that it works in that scenario. Also I have checked it adding to the 'List' yet I am receiving the same error. [looked into this as well](https://github.com/GeekyAnts/NativeBase/issues/348#issuecomment-269209129)

**Comment by SupriyaKalghatgi** [comment]
Tried this https://github.com/GeekyAnts/NativeBase/issues/348#issuecomment-266285965

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/1720#issuecomment-376062502

**Comment by saurabhabh** [comment]
How is the code in the 2 mentioned comments different from what I have written ? I have done the same thing and it doesnt work for me . Is it because I have a 'List' inside my 'Content' ?

**Comment by SupriyaKalghatgi** [comment]
I would suggest to try both these snippets
with List try this too https://github.com/GeekyAnts/NativeBase/issues/348#issuecomment-269958631

**Comment by saurabhabh** [comment]
I found the problem. It was a silly issue.
![image](https://user-images.githubusercontent.com/8706481/45010164-a8fb7680-b029-11e8-841f-637a880d1d63.png)

After changing this to the handle of the function it works. 
Thanks for the support
