### ISSUE TITLE
Text on Segment tabs disappearing after selecting inactive tab

### ISSUE THREAD

**Issue by michaelimstepf** [GeekyAnts/NativeBase#712]
Hi

I created a `Segment` with some logic to activate / deactivate tabs on a Segment and when I select the non active tab the text disappears on both tabs (the font color matches the changed background).

![screen shot 2017-04-04 at 4 51 29 pm](https://cloud.githubusercontent.com/assets/430682/24645327/080ad146-195b-11e7-9c77-66f5a4b5bb78.png)
![screen shot 2017-04-04 at 4 51 38 pm](https://cloud.githubusercontent.com/assets/430682/24645331/0af9c268-195b-11e7-8ad2-d7980de911e6.png)

```
import React, { Component } from 'react';
import { Container, Content, Header, Segment, Body, Button, Text, Left, Right, Icon } from 'native-base';

export default class JobsList extends Component {
  state = {
    activeTab: 'availableJobs'
  };

  onTabPress(tab) {
    this.setState({ activeTab: tab });
  }

  render() {
    return (
      <Container>
        <Header hasSegment>
          <Left />
          <Body>
            <Segment>
              <Button first active={this.state.activeTab === 'availableJobs'} onPress={() => this.onTabPress('availableJobs')}><Text>Available</Text></Button>
              <Button last active={this.state.activeTab === 'acceptedJobs'} onPress={() => this.onTabPress('acceptedJobs')}><Text>Accepted</Text></Button>
            </Segment>
          </Body>
          <Right />
        </Header>
        <Content>
        </Content>
      </Container>
    );
  }
}
```

## react-native, react and native-base version
```
  "dependencies": {
    "native-base": "^2.0.12",
    "react": "15.4.2",
    "react-native": "0.40.0",
    "react-native-button": "^1.8.2",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0"
  }
```
## Expected behaviour
After clicking on any tab, the text on both tabs should not be invisible / disappear
## Actual behaviour
After clicking on any tab, the text on both tabs becomes invisible / disappears
## Steps to reproduce (code snippet or screenshot)
See above
## Screenshot of emulator/device
See above 
## Is the bug present in both ios and android or in any one of them?
Only tested on iOS
## Any other additional info which would help us debug the issue quicker.
I hope it's not my code that is wrong?

**Comment by leyuan** [comment]
I have run into same issue, seems like in the recent update, the toggle will mis-change the font's colour.

**Comment by himanshu-satija** [comment]
@leyuan @michaelimstepf You shouldn't have to set active prop on Text. It was an issue with our forked version of @shoutem/theme.
Running `npm uninstall native-base && npm install native-base` should fix it.

**Comment by leyuan** [comment]
@himanshu-satija that did fix for me, thanks!

**Comment by michaelimstepf** [comment]
@himanshu-satija Thanks. I tried that but no I can't start the app anymore. I get the following message and I followed all the 3 steps but it still doesn't work.

```
~/Dev/CrewApp/node_modules/react-native/packager ~
Scanning 667 folders for symlinks in /Users/michaelimstepf/Dev/CrewApp/node_modules (26ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/michaelimstepf/Dev/CrewApp 

[04/11/2017, 17:34:25] <START> Initializing Packager
[04/11/2017, 17:34:25]         HMR Server listening on /hot

React packager ready.

[04/11/2017, 17:34:26] <START> Building Haste Map
[04/11/2017, 17:34:26] <END>   Building Haste Map (219ms)
[04/11/2017, 17:34:26] <END>   Initializing Packager (1042ms)
[04/11/2017, 17:34:36] <START> Requesting bundle
                               bundle_url: /index.ios.bundle?platform=ios&dev=true&minify=false
[04/11/2017, 17:34:36] <START> Transforming files
[04/11/2017, 17:34:36] <START> Requesting bundle
                               bundle_url: /index.ios.bundle?platform=ios&dev=true&minify=false&hot=true
[04/11/2017, 17:34:36] <START> Transforming files
transformed 746/748 (100%)(node:83869) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3343): UnableToResolveError: Unable to resolve module react-native/Libraries/Components/StaticContainer.react from /Users/michaelimstepf/Dev/CrewApp/node_modules/native-base/dist/src/basic/Tabs/SceneComponent.js: Module does not exist in the module map or in these directories:
  /Users/michaelimstepf/Dev/CrewApp/node_modules/react-native/Libraries/Components

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
(node:83869) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
transformed 792/794 (100%)(node:83869) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3344): UnableToResolveError: Unable to resolve module react-native/Libraries/Components/StaticContainer.react from /Users/michaelimstepf/Dev/CrewApp/node_modules/native-base/dist/src/basic/Tabs/SceneComponent.js: Module does not exist in the module map or in these directories:
  /Users/michaelimstepf/Dev/CrewApp/node_modules/react-native/Libraries/Components

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
```

**Comment by michaelimstepf** [comment]
@himanshu-satija Worked for me as well after upgrading React / React Native. Thanks!
