### ISSUE TITLE
UNMET PEER DEPENDENCIES

### ISSUE THREAD

**Issue by emekalites** [GeekyAnts/NativeBase#806]
`Hi,`
These are the versions for my react native application
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
"react-native-vector-icons": "^4.0.1"

While installing native-base@2.1.3, i ran into this issues:
```
npm WARN @shoutem/animation@0.8.10 requires a peer of react@^15.0.0 but none was installed.
npm WARN native-base-shoutem-theme@0.1.3 requires a peer of react@>=15.1.0 but none was installed.
npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
```

Please i need an advice on how i can install native-base to work with my current versions or do i have to downgrade to a lower version of react-native that supports react@^15.0.0

**Comment by yogeshmoradiya121** [comment]
same problem

**Comment by iegik** [comment]
Same problem:

```
npm WARN native-base@2.1.3 requires a peer of react@>=16.0.0-alpha.3 but none was installed.
npm WARN native-base@2.1.3 requires a peer of react-native-vector-icons@~4.0.0 but none was installed.
```

**Comment by a-shark** [comment]
Same `shoutem` issues, but trying to use RN `0.43.0`, not `0.44.0`.

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.1.4](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.1.4)

**Comment by jpgnotgif** [comment]
@SupriyaKalghatgi Has this fix been verified by anyone above or on the GeekyAnts team? ( @emekalites, @yogeshmoradiya121, @iegik or @a-shark)? I'm still seeing this issue.

How I'm installing nativebase: ```npm install native-base@2.1.4 -S```

A portion of my package.json

```
  "dependencies": {
    "native-base": "^2.1.4",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.2"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "1.9.2",
    "eslint": "^3.19.0",
    "eslint-plugin-react": "^7.0.1",
    "eslint-plugin-react-native": "^2.3.2",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.6"
  }
```

**Comment by iegik** [comment]
```
├─┬ native-base@2.1.4 
│ ├─┬ @shoutem/animation@0.8.10 
│ │ └── lodash@4.17.4 
│ ├── blueimp-md5@2.7.0 
│ ├── clamp@1.0.1 
│ ├─┬ color@0.11.4 
│ │ ├── clone@1.0.2 
│ │ ├─┬ color-convert@1.9.0 
│ │ │ └── color-name@1.1.2 
│ │ └── color-string@0.3.0 
│ ├─┬ fs-extra@2.1.2 
│ │ └── jsonfile@2.4.0 
│ ├── lodash@4.11.2 
│ ├── native-base-shoutem-theme@0.1.4 
│ ├── print-message@2.1.0 
│ ├── UNMET PEER DEPENDENCY react@^15.0.0
│ ├── react-native-drawer@2.3.0 
│ ├── react-native-easy-grid@0.1.7 
│ ├── react-native-keyboard-aware-scroll-view@0.2.7 
│ ├── react-native-vector-icons@4.1.1 
│ ├─┬ react-tween-state@0.1.5 
│ │ └─┬ raf@3.3.2 
│ │   └── performance-now@2.1.0 
│ └── tween-functions@1.2.0 

npm WARN native-base-shoutem-theme@0.1.4 requires a peer of react@>=15.1.0 but none was installed.
npm WARN @shoutem/animation@0.8.10 requires a peer of react@^15.0.0 but none was installed.
```

**Comment by emekalites** [comment]
@SupriyaKalghatgi this issue hasnt been fixed at all

**Comment by sankhadeeproy007** [comment]
Hi, apart from the warning, are you facing any problems using the library?

**Comment by emekalites** [comment]
@sankhadeeproy007 ReactNative@0.42.3, react@15.4.2 with native-base@2.1.0 works well. Using anything higher than the said versions of RN and react is the issue.

**Comment by sankhadeeproy007** [comment]
Okay, thanks for the info, will be fixed tomorrow in the new patch :)

**Comment by SupriyaKalghatgi** [comment]
Check NativeBase 2.1.5

**Comment by iegik** [comment]
```
├─┬ native-base@2.1.5 
│ ├─┬ color@1.0.3 
│ │ └─┬ color-string@1.5.2 
│ │   └─┬ simple-swizzle@0.2.2 
│ │     └── is-arrayish@0.3.1 
│ ├── native-base-shoutem-theme@0.1.7 
│ ├── UNMET PEER DEPENDENCY react@^15.0.0
│ └── react-native-keyboard-aware-scroll-view@0.2.9 
└── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
```

**Comment by iegik** [comment]
2.1.5 craches my app in several places!

2.1.4
```
        return color(this.toolbarDefaultBg).darken(0.2).hexString();
```
->
2.1.5
```
        return color(this.toolbarDefaultBg).darken(0.2).hex();
```

**Comment by didil** [comment]
changing .hexString() to .hex() everywhere worked for me

**Comment by iegik** [comment]
https://github.com/GeekyAnts/NativeBase/issues/937

**Comment by iegik** [comment]
https://github.com/GeekyAnts/NativeBase/pull/939

**Comment by leu2tm** [comment]
` 
 "dependencies": {
     "native-base": "^2.1.4",

     "react": "16.0.0-alpha.12",

     "react-native": "0.46.1"

  }
`

**Comment by ohir** [comment]
Acked: with fresh react-native init then native-base install I got outdated dependency
...
warning: "@shoutem/animation@0.8.10" has incorrect peer dependency "react@^15.0.0".
...

package.json:
"native-base": "2.2.1"
"react": "16.0.0-alpha.12"
"react-native": "0.46.1"

**Comment by soleverlee** [comment]
same problem

**Comment by nonameolsson** [comment]
Why does we need to to this? https://github.com/GeekyAnts/NativeBase/issues/806#issuecomment-307763607

**Comment by shivrajkumar** [comment]
@nonameolsson Thats because of the version upgrade of color package. With version 1.x of color, the use case had changed a bit

**Comment by iegik** [comment]
native-base@2.2.1 requires `print-message`

```
npm install print-message@2.1.0 --save
npm i native-base@2.2.1 --save
```
