### ISSUE TITLE
Toast setState error: Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ToastContainer component.

### ISSUE THREAD

**Issue by abser** [GeekyAnts/NativeBase#819]
On    "native-base": "2.1.0" with 
    "react": "^15.4.2"
and 
    "react-native": "^0.42.3",

I am getting below error when app navigates to another screen:
"Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ToastContainer component."

My component code:

componentWillReceiveProps(nextProps) {
// Checking if there is login error and show the toast mesasge  
if (nextProps.loginErrorMsg) {
	Toast.show({
		text: nextProps.loginErrorMsg,
		position: 'top',
		type: 'danger',
		duration: 4000
	});
}
// Naviagte to TabBarController after successful login.
if (nextProps.loggedIn) {
			nextProps.navigator.resetTo({
				screen: 'mc.TabBarController',
				animated: true,
			});
		}
}

Test steps scenario:
1. Login with wrong user or password shows the Toast.
2. Next Login with valid user and password. No need to show the toast.
3. User successfully login
4. App Navigate to TabBarController and show the error.

**Comment by sankhadeeproy007** [comment]
Fixed with 2.1.5

**Comment by bm-software** [comment]
This issue is not fixed. I'm using

- react-native: 0.46.4
- native-base: 2.3.1

I think that [this issue](https://github.com/GeekyAnts/NativeBase/issues/739) is caused by that warning. I'm experiencing both.

How can I solve?

**Comment by daton89** [comment]
Maybe this could help: 

```js
import { Root } from "native-base";
import { StackNavigator } from "react-navigation";
const AppNavigator = StackNavigator(
  {
    Page: { screen: Page },
  }
);
export default () =>
  <Root>
    <AppNavigator />
  </Root>;
```

**Comment by bing-deng** [comment]
> Maybe this could help:
> 
> ```js
> import { Root } from "native-base";
> import { StackNavigator } from "react-navigation";
> const AppNavigator = StackNavigator(
>   {
>     Page: { screen: Page },
>   }
> );
> export default () =>
>   <Root>
>     <AppNavigator />
>   </Root>;
> ```

it works for me

**Comment by lucasklaassen** [comment]
If anyone comes to this post in the future because they are getting a `no-op` error still, make sure you are not including a `<Root>` component inside of another `<Root>` component.

ie.

```
import { Root } from "native-base";
import { StackNavigator } from "react-navigation";
const AppNavigator = StackNavigator(
  {
    Page: { screen: Page },
  }
);
export default () =>
  <Root>
    <AppNavigator />
  </Root>;
```

```
export default class EnterUsernameScreen extends React.Component {

  constructor(props) {
    super(props);
...
render() {
  return {
    <Root>
...
```

**Comment by Aryk** [comment]
> If anyone comes to this post in the future because they are getting a `no-op` error still, make sure you are not including a `<Root>` component inside of another `<Root>` component.
> 
> ie.
> 
> ```
> import { Root } from "native-base";
> import { StackNavigator } from "react-navigation";
> const AppNavigator = StackNavigator(
>   {
>     Page: { screen: Page },
>   }
> );
> export default () =>
>   <Root>
>     <AppNavigator />
>   </Root>;
> ```
> 
> ```
> export default class EnterUsernameScreen extends React.Component {
> 
>   constructor(props) {
>     super(props);
> ...
> render() {
>   return {
>     <Root>
> ...
> ```

The only issue is that, if you use transparentModal from createNativeTabNavigator on react-navigation, you have to use <Roo> again within that if you want modals to show up.

Are you familiar with that issue? Any suggestions around it?
