### ISSUE TITLE
Toast Not Displaying

### ISSUE THREAD

**Issue by muthuraman007** [GeekyAnts/NativeBase#949]
Hi,
I have two pages PageA and PageB,
 Page A has a  2 buttons, one for page navigation and other for displaying toast message.
When Page A loads first time ,it displays toast when i press DisplayToast button then i click navigate button it  goes to pageB and i press back button it goes to its previous page (Page A) .

After back flow when i click toast button in PageA it doesn't displaying toast and produces following error,
`TypeError: Cannot read property '_root' of null`

native base : "2.1.1"
react: "15.4.2",
react-native: "0.42.3",

**Comment by shivrajkumar** [comment]
#836

**Comment by shivrajkumar** [comment]
Fixed with v2.1.5

**Comment by tocttou** [comment]
I am still facing the same issue as #836.

"native-base": "^2.1.5"
"react": "16.0.0-alpha.12"
"react-native": "0.45.1"
